# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Learning.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1046, 507)
        self.testResultSave_Button = QtWidgets.QPushButton(Dialog)
        self.testResultSave_Button.setGeometry(QtCore.QRect(370, 460, 150, 40))
        self.testResultSave_Button.setObjectName("testResultSave_Button")
        self.weightAndBiasSave_Button = QtWidgets.QPushButton(Dialog)
        self.weightAndBiasSave_Button.setGeometry(QtCore.QRect(530, 460, 150, 40))
        self.weightAndBiasSave_Button.setObjectName("weightAndBiasSave_Button")
        self.pause_Button = QtWidgets.QPushButton(Dialog)
        self.pause_Button.setEnabled(False)
        self.pause_Button.setGeometry(QtCore.QRect(170, 460, 150, 40))
        self.pause_Button.setObjectName("pause_Button")
        self.Status_GroupBox = QtWidgets.QGroupBox(Dialog)
        self.Status_GroupBox.setGeometry(QtCore.QRect(10, 10, 1021, 441))
        self.Status_GroupBox.setObjectName("Status_GroupBox")
        self.displayMode_Label = QtWidgets.QLabel(self.Status_GroupBox)
        self.displayMode_Label.setGeometry(QtCore.QRect(890, 100, 81, 16))
        self.displayMode_Label.setObjectName("displayMode_Label")
        self.displayMode_ComboBox = QtWidgets.QComboBox(self.Status_GroupBox)
        self.displayMode_ComboBox.setGeometry(QtCore.QRect(890, 120, 121, 22))
        self.displayMode_ComboBox.setObjectName("displayMode_ComboBox")
        self.displayMode_ComboBox.addItem("")
        self.displayMode_ComboBox.addItem("")
        self.displayMode_ComboBox.addItem("")
        self.yAxis_label = QtWidgets.QLabel(self.Status_GroupBox)
        self.yAxis_label.setGeometry(QtCore.QRect(890, 150, 47, 13))
        self.yAxis_label.setObjectName("yAxis_label")
        self.label_3 = QtWidgets.QLabel(self.Status_GroupBox)
        self.label_3.setGeometry(QtCore.QRect(940, 170, 21, 16))
        self.label_3.setObjectName("label_3")
        self.yAxisMin_LineEdit = QtWidgets.QLineEdit(self.Status_GroupBox)
        self.yAxisMin_LineEdit.setGeometry(QtCore.QRect(890, 170, 41, 20))
        self.yAxisMin_LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.yAxisMin_LineEdit.setObjectName("yAxisMin_LineEdit")
        self.yAxisMax_LineEdit = QtWidgets.QLineEdit(self.Status_GroupBox)
        self.yAxisMax_LineEdit.setGeometry(QtCore.QRect(960, 170, 41, 20))
        self.yAxisMax_LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.yAxisMax_LineEdit.setObjectName("yAxisMax_LineEdit")
        self.cycle_CheckBox = QtWidgets.QCheckBox(self.Status_GroupBox)
        self.cycle_CheckBox.setGeometry(QtCore.QRect(890, 200, 101, 17))
        self.cycle_CheckBox.setObjectName("cycle_CheckBox")
        self.result_Display_Button = QtWidgets.QPushButton(self.Status_GroupBox)
        self.result_Display_Button.setGeometry(QtCore.QRect(942, 217, 70, 23))
        self.result_Display_Button.setObjectName("result_Display_Button")
        self.totalEpoch_Label = QtWidgets.QLabel(self.Status_GroupBox)
        self.totalEpoch_Label.setGeometry(QtCore.QRect(890, 290, 120, 13))
        self.totalEpoch_Label.setObjectName("totalEpoch_Label")
        self.currentLearningSetup_Label = QtWidgets.QLabel(self.Status_GroupBox)
        self.currentLearningSetup_Label.setGeometry(QtCore.QRect(890, 340, 120, 13))
        self.currentLearningSetup_Label.setObjectName("currentLearningSetup_Label")
        self.currentEpoch_Label = QtWidgets.QLabel(self.Status_GroupBox)
        self.currentEpoch_Label.setGeometry(QtCore.QRect(890, 390, 120, 13))
        self.currentEpoch_Label.setObjectName("currentEpoch_Label")
        self.currentEpoch_LineEdit = QtWidgets.QLineEdit(self.Status_GroupBox)
        self.currentEpoch_LineEdit.setGeometry(QtCore.QRect(890, 410, 121, 20))
        self.currentEpoch_LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.currentEpoch_LineEdit.setReadOnly(True)
        self.currentEpoch_LineEdit.setObjectName("currentEpoch_LineEdit")
        self.totalEpoch_LineEdit = QtWidgets.QLineEdit(self.Status_GroupBox)
        self.totalEpoch_LineEdit.setGeometry(QtCore.QRect(890, 310, 121, 20))
        self.totalEpoch_LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.totalEpoch_LineEdit.setReadOnly(True)
        self.totalEpoch_LineEdit.setObjectName("totalEpoch_LineEdit")
        self.currentLearningSetup_LineEdit = QtWidgets.QLineEdit(self.Status_GroupBox)
        self.currentLearningSetup_LineEdit.setGeometry(QtCore.QRect(890, 360, 121, 20))
        self.currentLearningSetup_LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.currentLearningSetup_LineEdit.setReadOnly(True)
        self.currentLearningSetup_LineEdit.setObjectName("currentLearningSetup_LineEdit")
        self.graph_Widget = QtWidgets.QWidget(self.Status_GroupBox)
        self.graph_Widget.setGeometry(QtCore.QRect(10, 20, 871, 411))
        self.graph_Widget.setObjectName("graph_Widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.graph_Widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 431, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.weightGraphLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.weightGraphLayout.setContentsMargins(0, 0, 0, 0)
        self.weightGraphLayout.setObjectName("weightGraphLayout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.graph_Widget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(440, 0, 421, 411))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.progressGraphLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.progressGraphLayout.setContentsMargins(0, 0, 0, 0)
        self.progressGraphLayout.setObjectName("progressGraphLayout")
        self.macro_Label = QtWidgets.QLabel(self.Status_GroupBox)
        self.macro_Label.setGeometry(QtCore.QRect(890, 240, 120, 13))
        self.macro_Label.setObjectName("macro_Label")
        self.macro_LineEdit = QtWidgets.QLineEdit(self.Status_GroupBox)
        self.macro_LineEdit.setGeometry(QtCore.QRect(890, 260, 121, 20))
        self.macro_LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.macro_LineEdit.setReadOnly(True)
        self.macro_LineEdit.setObjectName("macro_LineEdit")
        self.displayWeight_Label = QtWidgets.QLabel(self.Status_GroupBox)
        self.displayWeight_Label.setGeometry(QtCore.QRect(890, 20, 81, 16))
        self.displayWeight_Label.setObjectName("displayWeight_Label")
        self.weightName_ComboBox = QtWidgets.QComboBox(self.Status_GroupBox)
        self.weightName_ComboBox.setGeometry(QtCore.QRect(890, 40, 121, 22))
        self.weightName_ComboBox.setObjectName("weightName_ComboBox")
        self.weight_Display_Button = QtWidgets.QPushButton(self.Status_GroupBox)
        self.weight_Display_Button.setGeometry(QtCore.QRect(940, 70, 70, 23))
        self.weight_Display_Button.setObjectName("weight_Display_Button")
        self.start_Button = QtWidgets.QPushButton(Dialog)
        self.start_Button.setGeometry(QtCore.QRect(10, 460, 150, 40))
        self.start_Button.setObjectName("start_Button")
        self.exit_Button = QtWidgets.QPushButton(Dialog)
        self.exit_Button.setGeometry(QtCore.QRect(880, 460, 150, 40))
        self.exit_Button.setObjectName("exit_Button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.testResultSave_Button.setText(_translate("Dialog", "Test Result Save (TXT)"))
        self.weightAndBiasSave_Button.setText(_translate("Dialog", "Weight && Bias Save"))
        self.pause_Button.setText(_translate("Dialog", "Pause"))
        self.Status_GroupBox.setTitle(_translate("Dialog", "Status"))
        self.displayMode_Label.setText(_translate("Dialog", "Progress Display"))
        self.displayMode_ComboBox.setItemText(0, _translate("Dialog", "Mean Squared Error"))
        self.displayMode_ComboBox.setItemText(1, _translate("Dialog", "Cross Entropy"))
        self.displayMode_ComboBox.setItemText(2, _translate("Dialog", "Semantic Stress"))
        self.yAxis_label.setText(_translate("Dialog", "Y-Axis"))
        self.label_3.setText(_translate("Dialog", "~"))
        self.yAxisMin_LineEdit.setText(_translate("Dialog", "-0.01"))
        self.yAxisMax_LineEdit.setText(_translate("Dialog", "1.01"))
        self.cycle_CheckBox.setText(_translate("Dialog", "Use Cycle"))
        self.result_Display_Button.setText(_translate("Dialog", "Display"))
        self.totalEpoch_Label.setText(_translate("Dialog", "Total Epoch"))
        self.currentLearningSetup_Label.setText(_translate("Dialog", "Current Learning Setup"))
        self.currentEpoch_Label.setText(_translate("Dialog", "Current Epoch"))
        self.currentEpoch_LineEdit.setText(_translate("Dialog", "-"))
        self.totalEpoch_LineEdit.setText(_translate("Dialog", "-"))
        self.currentLearningSetup_LineEdit.setText(_translate("Dialog", "-"))
        self.macro_Label.setText(_translate("Dialog", "Macro Status"))
        self.macro_LineEdit.setText(_translate("Dialog", "-"))
        self.displayWeight_Label.setText(_translate("Dialog", "Weight Display"))
        self.weight_Display_Button.setText(_translate("Dialog", "Display"))
        self.start_Button.setText(_translate("Dialog", "Start"))
        self.exit_Button.setText(_translate("Dialog", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

