# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Macro.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(990, 636)
        self.fileLoad_GroupBox = QtWidgets.QGroupBox(Dialog)
        self.fileLoad_GroupBox.setGeometry(QtCore.QRect(10, 10, 391, 71))
        self.fileLoad_GroupBox.setObjectName("fileLoad_GroupBox")
        self.baseModelDataFile_Label = QtWidgets.QLabel(self.fileLoad_GroupBox)
        self.baseModelDataFile_Label.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.baseModelDataFile_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.baseModelDataFile_Label.setObjectName("baseModelDataFile_Label")
        self.baseModelDataFile_LineEdit = QtWidgets.QLineEdit(self.fileLoad_GroupBox)
        self.baseModelDataFile_LineEdit.setGeometry(QtCore.QRect(10, 40, 191, 20))
        self.baseModelDataFile_LineEdit.setReadOnly(True)
        self.baseModelDataFile_LineEdit.setObjectName("baseModelDataFile_LineEdit")
        self.baseModelDataFileBroswer_Button = QtWidgets.QPushButton(self.fileLoad_GroupBox)
        self.baseModelDataFileBroswer_Button.setGeometry(QtCore.QRect(210, 40, 81, 23))
        self.baseModelDataFileBroswer_Button.setObjectName("baseModelDataFileBroswer_Button")
        self.baseModelDataFileLoad_Button = QtWidgets.QPushButton(self.fileLoad_GroupBox)
        self.baseModelDataFileLoad_Button.setGeometry(QtCore.QRect(300, 40, 81, 23))
        self.baseModelDataFileLoad_Button.setObjectName("baseModelDataFileLoad_Button")
        self.groupBox_ = QtWidgets.QGroupBox(Dialog)
        self.groupBox_.setEnabled(False)
        self.groupBox_.setGeometry(QtCore.QRect(410, 230, 571, 361))
        self.groupBox_.setObjectName("groupBox_")
        self.modifyFactorDelete_Button = QtWidgets.QPushButton(self.groupBox_)
        self.modifyFactorDelete_Button.setGeometry(QtCore.QRect(10, 140, 211, 30))
        self.modifyFactorDelete_Button.setObjectName("modifyFactorDelete_Button")
        self.macroSize_Label = QtWidgets.QLabel(self.groupBox_)
        self.macroSize_Label.setGeometry(QtCore.QRect(230, 10, 51, 21))
        self.macroSize_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.macroSize_Label.setObjectName("macroSize_Label")
        self.macroSize_LineEdit = QtWidgets.QLineEdit(self.groupBox_)
        self.macroSize_LineEdit.setGeometry(QtCore.QRect(230, 30, 331, 21))
        self.macroSize_LineEdit.setAutoFillBackground(False)
        self.macroSize_LineEdit.setText("")
        self.macroSize_LineEdit.setReadOnly(True)
        self.macroSize_LineEdit.setObjectName("macroSize_LineEdit")
        self.modifyFactor_ListWidget = QtWidgets.QListWidget(self.groupBox_)
        self.modifyFactor_ListWidget.setGeometry(QtCore.QRect(10, 20, 211, 121))
        self.modifyFactor_ListWidget.setObjectName("modifyFactor_ListWidget")
        self.macroAdd_Button = QtWidgets.QPushButton(self.groupBox_)
        self.macroAdd_Button.setGeometry(QtCore.QRect(440, 60, 120, 30))
        self.macroAdd_Button.setObjectName("macroAdd_Button")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_)
        self.tabWidget.setGeometry(QtCore.QRect(10, 180, 551, 171))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layerSizeFrom_LineEdit = QtWidgets.QLineEdit(self.tab)
        self.layerSizeFrom_LineEdit.setGeometry(QtCore.QRect(90, 40, 60, 20))
        self.layerSizeFrom_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layerSizeFrom_LineEdit.setObjectName("layerSizeFrom_LineEdit")
        self.layerSizeStep_LineEdit = QtWidgets.QLineEdit(self.tab)
        self.layerSizeStep_LineEdit.setGeometry(QtCore.QRect(270, 40, 60, 20))
        self.layerSizeStep_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layerSizeStep_LineEdit.setObjectName("layerSizeStep_LineEdit")
        self.layerSizeLayer_ComboBox = QtWidgets.QComboBox(self.tab)
        self.layerSizeLayer_ComboBox.setGeometry(QtCore.QRect(90, 10, 101, 22))
        self.layerSizeLayer_ComboBox.setObjectName("layerSizeLayer_ComboBox")
        self.layerSize_Label = QtWidgets.QLabel(self.tab)
        self.layerSize_Label.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.layerSize_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layerSize_Label.setObjectName("layerSize_Label")
        self.layerSizeTo_LineEdit = QtWidgets.QLineEdit(self.tab)
        self.layerSizeTo_LineEdit.setGeometry(QtCore.QRect(170, 40, 60, 20))
        self.layerSizeTo_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layerSizeTo_LineEdit.setObjectName("layerSizeTo_LineEdit")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(240, 40, 31, 21))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(153, 40, 16, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.layerSizeAdd_Button = QtWidgets.QPushButton(self.tab)
        self.layerSizeAdd_Button.setGeometry(QtCore.QRect(440, 100, 100, 30))
        self.layerSizeAdd_Button.setObjectName("layerSizeAdd_Button")
        self.layerSize_Label_2 = QtWidgets.QLabel(self.tab)
        self.layerSize_Label_2.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.layerSize_Label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layerSize_Label_2.setObjectName("layerSize_Label_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.regularMultiLayerSizeTo_Label = QtWidgets.QLabel(self.tab_6)
        self.regularMultiLayerSizeTo_Label.setGeometry(QtCore.QRect(153, 70, 16, 21))
        self.regularMultiLayerSizeTo_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.regularMultiLayerSizeTo_Label.setObjectName("regularMultiLayerSizeTo_Label")
        self.regularMultiLayerSizeRange_Label = QtWidgets.QLabel(self.tab_6)
        self.regularMultiLayerSizeRange_Label.setGeometry(QtCore.QRect(10, 70, 71, 21))
        self.regularMultiLayerSizeRange_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.regularMultiLayerSizeRange_Label.setObjectName("regularMultiLayerSizeRange_Label")
        self.regularMultiLayerSizeTo_LineEdit = QtWidgets.QLineEdit(self.tab_6)
        self.regularMultiLayerSizeTo_LineEdit.setGeometry(QtCore.QRect(170, 70, 60, 20))
        self.regularMultiLayerSizeTo_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.regularMultiLayerSizeTo_LineEdit.setObjectName("regularMultiLayerSizeTo_LineEdit")
        self.regularMultiLayerSizeStep_Label = QtWidgets.QLabel(self.tab_6)
        self.regularMultiLayerSizeStep_Label.setGeometry(QtCore.QRect(240, 70, 31, 21))
        self.regularMultiLayerSizeStep_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.regularMultiLayerSizeStep_Label.setObjectName("regularMultiLayerSizeStep_Label")
        self.regularMultiLayerSizeStep_LineEdit = QtWidgets.QLineEdit(self.tab_6)
        self.regularMultiLayerSizeStep_LineEdit.setGeometry(QtCore.QRect(270, 70, 60, 20))
        self.regularMultiLayerSizeStep_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.regularMultiLayerSizeStep_LineEdit.setObjectName("regularMultiLayerSizeStep_LineEdit")
        self.regularMultiLayerSizeFrom_LineEdit = QtWidgets.QLineEdit(self.tab_6)
        self.regularMultiLayerSizeFrom_LineEdit.setGeometry(QtCore.QRect(90, 70, 60, 20))
        self.regularMultiLayerSizeFrom_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.regularMultiLayerSizeFrom_LineEdit.setObjectName("regularMultiLayerSizeFrom_LineEdit")
        self.regularMultiLayerSizeLayerPrefix_Label = QtWidgets.QLabel(self.tab_6)
        self.regularMultiLayerSizeLayerPrefix_Label.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.regularMultiLayerSizeLayerPrefix_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.regularMultiLayerSizeLayerPrefix_Label.setObjectName("regularMultiLayerSizeLayerPrefix_Label")
        self.regularMultiLayerSizeLayerPrefix_LineEdit = QtWidgets.QLineEdit(self.tab_6)
        self.regularMultiLayerSizeLayerPrefix_LineEdit.setGeometry(QtCore.QRect(90, 10, 113, 20))
        self.regularMultiLayerSizeLayerPrefix_LineEdit.setObjectName("regularMultiLayerSizeLayerPrefix_LineEdit")
        self.regularMultiLayerSizeMaxSuffix_LineEdit = QtWidgets.QLineEdit(self.tab_6)
        self.regularMultiLayerSizeMaxSuffix_LineEdit.setGeometry(QtCore.QRect(90, 40, 61, 20))
        self.regularMultiLayerSizeMaxSuffix_LineEdit.setObjectName("regularMultiLayerSizeMaxSuffix_LineEdit")
        self.regularMultiLayerSizeMaxSuffix_Label = QtWidgets.QLabel(self.tab_6)
        self.regularMultiLayerSizeMaxSuffix_Label.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.regularMultiLayerSizeMaxSuffix_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.regularMultiLayerSizeMaxSuffix_Label.setObjectName("regularMultiLayerSizeMaxSuffix_Label")
        self.regularMultiLayerSizeAdd_Button = QtWidgets.QPushButton(self.tab_6)
        self.regularMultiLayerSizeAdd_Button.setGeometry(QtCore.QRect(440, 100, 100, 30))
        self.regularMultiLayerSizeAdd_Button.setObjectName("regularMultiLayerSizeAdd_Button")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.irregularMultiLayerSizeLayer_Label = QtWidgets.QLabel(self.tab_7)
        self.irregularMultiLayerSizeLayer_Label.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.irregularMultiLayerSizeLayer_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.irregularMultiLayerSizeLayer_Label.setObjectName("irregularMultiLayerSizeLayer_Label")
        self.irregularMultiLayerSizeTo_Label = QtWidgets.QLabel(self.tab_7)
        self.irregularMultiLayerSizeTo_Label.setGeometry(QtCore.QRect(153, 40, 16, 21))
        self.irregularMultiLayerSizeTo_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.irregularMultiLayerSizeTo_Label.setObjectName("irregularMultiLayerSizeTo_Label")
        self.irregularMultiLayerSizeTo_LineEdit = QtWidgets.QLineEdit(self.tab_7)
        self.irregularMultiLayerSizeTo_LineEdit.setGeometry(QtCore.QRect(170, 40, 60, 20))
        self.irregularMultiLayerSizeTo_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.irregularMultiLayerSizeTo_LineEdit.setObjectName("irregularMultiLayerSizeTo_LineEdit")
        self.irregularMultiLayerSizeStep_Label = QtWidgets.QLabel(self.tab_7)
        self.irregularMultiLayerSizeStep_Label.setGeometry(QtCore.QRect(240, 40, 31, 21))
        self.irregularMultiLayerSizeStep_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.irregularMultiLayerSizeStep_Label.setObjectName("irregularMultiLayerSizeStep_Label")
        self.irregularMultiLayerSizeLayer_LineEdit = QtWidgets.QLineEdit(self.tab_7)
        self.irregularMultiLayerSizeLayer_LineEdit.setGeometry(QtCore.QRect(90, 10, 241, 20))
        self.irregularMultiLayerSizeLayer_LineEdit.setObjectName("irregularMultiLayerSizeLayer_LineEdit")
        self.irregularMultiLayerSizeStep_LineEdit = QtWidgets.QLineEdit(self.tab_7)
        self.irregularMultiLayerSizeStep_LineEdit.setGeometry(QtCore.QRect(270, 40, 60, 20))
        self.irregularMultiLayerSizeStep_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.irregularMultiLayerSizeStep_LineEdit.setObjectName("irregularMultiLayerSizeStep_LineEdit")
        self.irregularMultiLayerSizeFrom_LineEdit = QtWidgets.QLineEdit(self.tab_7)
        self.irregularMultiLayerSizeFrom_LineEdit.setGeometry(QtCore.QRect(90, 40, 60, 20))
        self.irregularMultiLayerSizeFrom_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.irregularMultiLayerSizeFrom_LineEdit.setObjectName("irregularMultiLayerSizeFrom_LineEdit")
        self.irregularMultiLayerSizeRange_LineEdit = QtWidgets.QLabel(self.tab_7)
        self.irregularMultiLayerSizeRange_LineEdit.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.irregularMultiLayerSizeRange_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.irregularMultiLayerSizeRange_LineEdit.setObjectName("irregularMultiLayerSizeRange_LineEdit")
        self.irregularMultiLayerSizeAdd_Button = QtWidgets.QPushButton(self.tab_7)
        self.irregularMultiLayerSizeAdd_Button.setGeometry(QtCore.QRect(440, 100, 100, 30))
        self.irregularMultiLayerSizeAdd_Button.setObjectName("irregularMultiLayerSizeAdd_Button")
        self.irregularMultiLayerSizeNotice_Label = QtWidgets.QLabel(self.tab_7)
        self.irregularMultiLayerSizeNotice_Label.setGeometry(QtCore.QRect(340, 10, 201, 21))
        self.irregularMultiLayerSizeNotice_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.irregularMultiLayerSizeNotice_Label.setObjectName("irregularMultiLayerSizeNotice_Label")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.learningRateFrom_LineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.learningRateFrom_LineEdit.setGeometry(QtCore.QRect(90, 40, 60, 20))
        self.learningRateFrom_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.learningRateFrom_LineEdit.setObjectName("learningRateFrom_LineEdit")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(153, 40, 16, 21))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.learningRateTo_LineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.learningRateTo_LineEdit.setGeometry(QtCore.QRect(170, 40, 60, 20))
        self.learningRateTo_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.learningRateTo_LineEdit.setObjectName("learningRateTo_LineEdit")
        self.learningRateStep_LineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.learningRateStep_LineEdit.setGeometry(QtCore.QRect(270, 40, 60, 20))
        self.learningRateStep_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.learningRateStep_LineEdit.setObjectName("learningRateStep_LineEdit")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(240, 40, 31, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.learningRateAdd_Button = QtWidgets.QPushButton(self.tab_2)
        self.learningRateAdd_Button.setGeometry(QtCore.QRect(440, 100, 100, 30))
        self.learningRateAdd_Button.setObjectName("learningRateAdd_Button")
        self.layerSize_Label_3 = QtWidgets.QLabel(self.tab_2)
        self.layerSize_Label_3.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.layerSize_Label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layerSize_Label_3.setObjectName("layerSize_Label_3")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.initialWeightSDFrom_LineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.initialWeightSDFrom_LineEdit.setGeometry(QtCore.QRect(90, 40, 60, 20))
        self.initialWeightSDFrom_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.initialWeightSDFrom_LineEdit.setObjectName("initialWeightSDFrom_LineEdit")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(153, 40, 16, 21))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.initialWeightSDTo_LineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.initialWeightSDTo_LineEdit.setGeometry(QtCore.QRect(170, 40, 60, 20))
        self.initialWeightSDTo_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.initialWeightSDTo_LineEdit.setObjectName("initialWeightSDTo_LineEdit")
        self.initialWeightSDAdd_Button = QtWidgets.QPushButton(self.tab_3)
        self.initialWeightSDAdd_Button.setGeometry(QtCore.QRect(440, 100, 100, 30))
        self.initialWeightSDAdd_Button.setObjectName("initialWeightSDAdd_Button")
        self.initialWeightSDStep_LineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.initialWeightSDStep_LineEdit.setGeometry(QtCore.QRect(270, 40, 60, 20))
        self.initialWeightSDStep_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.initialWeightSDStep_LineEdit.setObjectName("initialWeightSDStep_LineEdit")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(240, 40, 31, 21))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.layerSize_Label_4 = QtWidgets.QLabel(self.tab_3)
        self.layerSize_Label_4.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.layerSize_Label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layerSize_Label_4.setObjectName("layerSize_Label_4")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.layerDamageSDTo_LineEdit = QtWidgets.QLineEdit(self.tab_4)
        self.layerDamageSDTo_LineEdit.setGeometry(QtCore.QRect(170, 70, 60, 20))
        self.layerDamageSDTo_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layerDamageSDTo_LineEdit.setObjectName("layerDamageSDTo_LineEdit")
        self.layerDamageSDAdd_Button = QtWidgets.QPushButton(self.tab_4)
        self.layerDamageSDAdd_Button.setGeometry(QtCore.QRect(440, 110, 100, 30))
        self.layerDamageSDAdd_Button.setObjectName("layerDamageSDAdd_Button")
        self.layerDamageSDFrom_LineEdit = QtWidgets.QLineEdit(self.tab_4)
        self.layerDamageSDFrom_LineEdit.setGeometry(QtCore.QRect(90, 70, 60, 20))
        self.layerDamageSDFrom_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layerDamageSDFrom_LineEdit.setObjectName("layerDamageSDFrom_LineEdit")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(153, 70, 16, 21))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.layerDamageSDProcess_ComboBox = QtWidgets.QComboBox(self.tab_4)
        self.layerDamageSDProcess_ComboBox.setGeometry(QtCore.QRect(90, 10, 101, 22))
        self.layerDamageSDProcess_ComboBox.setObjectName("layerDamageSDProcess_ComboBox")
        self.layerDamageSDOn_CheckBox = QtWidgets.QCheckBox(self.tab_4)
        self.layerDamageSDOn_CheckBox.setGeometry(QtCore.QRect(340, 70, 60, 17))
        self.layerDamageSDOn_CheckBox.setChecked(True)
        self.layerDamageSDOn_CheckBox.setObjectName("layerDamageSDOn_CheckBox")
        self.layerDamageSDStep_LineEdit = QtWidgets.QLineEdit(self.tab_4)
        self.layerDamageSDStep_LineEdit.setGeometry(QtCore.QRect(270, 70, 60, 20))
        self.layerDamageSDStep_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layerDamageSDStep_LineEdit.setObjectName("layerDamageSDStep_LineEdit")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(240, 70, 31, 21))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.layerDamageSDOff_CheckBox = QtWidgets.QCheckBox(self.tab_4)
        self.layerDamageSDOff_CheckBox.setGeometry(QtCore.QRect(410, 70, 60, 17))
        self.layerDamageSDOff_CheckBox.setObjectName("layerDamageSDOff_CheckBox")
        self.layerDamageSDLayer_ComboBox = QtWidgets.QComboBox(self.tab_4)
        self.layerDamageSDLayer_ComboBox.setGeometry(QtCore.QRect(90, 40, 101, 22))
        self.layerDamageSDLayer_ComboBox.setObjectName("layerDamageSDLayer_ComboBox")
        self.layerSize_Label_5 = QtWidgets.QLabel(self.tab_4)
        self.layerSize_Label_5.setGeometry(QtCore.QRect(10, 70, 71, 21))
        self.layerSize_Label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layerSize_Label_5.setObjectName("layerSize_Label_5")
        self.layerSize_Label_6 = QtWidgets.QLabel(self.tab_4)
        self.layerSize_Label_6.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.layerSize_Label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layerSize_Label_6.setObjectName("layerSize_Label_6")
        self.layerSize_Label_10 = QtWidgets.QLabel(self.tab_4)
        self.layerSize_Label_10.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.layerSize_Label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layerSize_Label_10.setObjectName("layerSize_Label_10")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.connectionDamageSDOff_CheckBox = QtWidgets.QCheckBox(self.tab_5)
        self.connectionDamageSDOff_CheckBox.setGeometry(QtCore.QRect(410, 70, 60, 17))
        self.connectionDamageSDOff_CheckBox.setObjectName("connectionDamageSDOff_CheckBox")
        self.label_15 = QtWidgets.QLabel(self.tab_5)
        self.label_15.setGeometry(QtCore.QRect(153, 70, 16, 21))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.connectionDamageSDStep_LineEdit = QtWidgets.QLineEdit(self.tab_5)
        self.connectionDamageSDStep_LineEdit.setGeometry(QtCore.QRect(270, 70, 60, 20))
        self.connectionDamageSDStep_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.connectionDamageSDStep_LineEdit.setObjectName("connectionDamageSDStep_LineEdit")
        self.connectionDamageSDOn_CheckBox = QtWidgets.QCheckBox(self.tab_5)
        self.connectionDamageSDOn_CheckBox.setGeometry(QtCore.QRect(340, 70, 60, 17))
        self.connectionDamageSDOn_CheckBox.setChecked(True)
        self.connectionDamageSDOn_CheckBox.setObjectName("connectionDamageSDOn_CheckBox")
        self.connectionDamageSDAdd_Button = QtWidgets.QPushButton(self.tab_5)
        self.connectionDamageSDAdd_Button.setGeometry(QtCore.QRect(440, 110, 100, 30))
        self.connectionDamageSDAdd_Button.setObjectName("connectionDamageSDAdd_Button")
        self.connectionDamageSDFrom_LineEdit = QtWidgets.QLineEdit(self.tab_5)
        self.connectionDamageSDFrom_LineEdit.setGeometry(QtCore.QRect(90, 70, 60, 20))
        self.connectionDamageSDFrom_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.connectionDamageSDFrom_LineEdit.setObjectName("connectionDamageSDFrom_LineEdit")
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        self.label_16.setGeometry(QtCore.QRect(240, 70, 31, 21))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.connectionDamageSDProcess_ComboBox = QtWidgets.QComboBox(self.tab_5)
        self.connectionDamageSDProcess_ComboBox.setGeometry(QtCore.QRect(90, 10, 101, 22))
        self.connectionDamageSDProcess_ComboBox.setObjectName("connectionDamageSDProcess_ComboBox")
        self.connectionDamageSDTo_LineEdit = QtWidgets.QLineEdit(self.tab_5)
        self.connectionDamageSDTo_LineEdit.setGeometry(QtCore.QRect(170, 70, 60, 20))
        self.connectionDamageSDTo_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.connectionDamageSDTo_LineEdit.setObjectName("connectionDamageSDTo_LineEdit")
        self.connectionDamageSDConnection_ComboBox = QtWidgets.QComboBox(self.tab_5)
        self.connectionDamageSDConnection_ComboBox.setGeometry(QtCore.QRect(90, 40, 101, 22))
        self.connectionDamageSDConnection_ComboBox.setObjectName("connectionDamageSDConnection_ComboBox")
        self.layerSize_Label_7 = QtWidgets.QLabel(self.tab_5)
        self.layerSize_Label_7.setGeometry(QtCore.QRect(10, 70, 71, 21))
        self.layerSize_Label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layerSize_Label_7.setObjectName("layerSize_Label_7")
        self.layerSize_Label_8 = QtWidgets.QLabel(self.tab_5)
        self.layerSize_Label_8.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.layerSize_Label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layerSize_Label_8.setObjectName("layerSize_Label_8")
        self.layerSize_Label_9 = QtWidgets.QLabel(self.tab_5)
        self.layerSize_Label_9.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.layerSize_Label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layerSize_Label_9.setObjectName("layerSize_Label_9")
        self.tabWidget.addTab(self.tab_5, "")
        self.baseModelStatus_GroupBox = QtWidgets.QGroupBox(Dialog)
        self.baseModelStatus_GroupBox.setGeometry(QtCore.QRect(10, 90, 391, 501))
        self.baseModelStatus_GroupBox.setObjectName("baseModelStatus_GroupBox")
        self.connection_Label = QtWidgets.QLabel(self.baseModelStatus_GroupBox)
        self.connection_Label.setGeometry(QtCore.QRect(200, 120, 100, 15))
        self.connection_Label.setObjectName("connection_Label")
        self.layer_Label = QtWidgets.QLabel(self.baseModelStatus_GroupBox)
        self.layer_Label.setGeometry(QtCore.QRect(10, 120, 100, 15))
        self.layer_Label.setObjectName("layer_Label")
        self.process_Label = QtWidgets.QLabel(self.baseModelStatus_GroupBox)
        self.process_Label.setGeometry(QtCore.QRect(200, 245, 100, 15))
        self.process_Label.setObjectName("process_Label")
        self.patternPack_Label = QtWidgets.QLabel(self.baseModelStatus_GroupBox)
        self.patternPack_Label.setGeometry(QtCore.QRect(10, 245, 100, 15))
        self.patternPack_Label.setObjectName("patternPack_Label")
        self.layer_ListWidget = QtWidgets.QListWidget(self.baseModelStatus_GroupBox)
        self.layer_ListWidget.setGeometry(QtCore.QRect(10, 135, 180, 110))
        self.layer_ListWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.layer_ListWidget.setObjectName("layer_ListWidget")
        self.connection_ListWidget = QtWidgets.QListWidget(self.baseModelStatus_GroupBox)
        self.connection_ListWidget.setGeometry(QtCore.QRect(200, 135, 180, 110))
        self.connection_ListWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.connection_ListWidget.setObjectName("connection_ListWidget")
        self.process_ListWidget = QtWidgets.QListWidget(self.baseModelStatus_GroupBox)
        self.process_ListWidget.setGeometry(QtCore.QRect(200, 260, 180, 110))
        self.process_ListWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.process_ListWidget.setObjectName("process_ListWidget")
        self.patternPack_ListWidget = QtWidgets.QListWidget(self.baseModelStatus_GroupBox)
        self.patternPack_ListWidget.setGeometry(QtCore.QRect(10, 260, 180, 110))
        self.patternPack_ListWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.patternPack_ListWidget.setObjectName("patternPack_ListWidget")
        self.learningSetup_Label = QtWidgets.QLabel(self.baseModelStatus_GroupBox)
        self.learningSetup_Label.setGeometry(QtCore.QRect(10, 370, 100, 15))
        self.learningSetup_Label.setObjectName("learningSetup_Label")
        self.learningSetup_ListWidget = QtWidgets.QListWidget(self.baseModelStatus_GroupBox)
        self.learningSetup_ListWidget.setGeometry(QtCore.QRect(10, 385, 180, 110))
        self.learningSetup_ListWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.learningSetup_ListWidget.setObjectName("learningSetup_ListWidget")
        self.configVariables_TextEdit = QtWidgets.QTextEdit(self.baseModelStatus_GroupBox)
        self.configVariables_TextEdit.setGeometry(QtCore.QRect(10, 40, 371, 81))
        self.configVariables_TextEdit.setReadOnly(True)
        self.configVariables_TextEdit.setObjectName("configVariables_TextEdit")
        self.layer_Label_2 = QtWidgets.QLabel(self.baseModelStatus_GroupBox)
        self.layer_Label_2.setGeometry(QtCore.QRect(10, 20, 100, 15))
        self.layer_Label_2.setObjectName("layer_Label_2")
        self.learning_Button = QtWidgets.QPushButton(Dialog)
        self.learning_Button.setGeometry(QtCore.QRect(280, 600, 120, 30))
        self.learning_Button.setObjectName("learning_Button")
        self.exit_Button = QtWidgets.QPushButton(Dialog)
        self.exit_Button.setGeometry(QtCore.QRect(570, 600, 120, 30))
        self.exit_Button.setObjectName("exit_Button")
        self.macroInformation_GroupBox = QtWidgets.QGroupBox(Dialog)
        self.macroInformation_GroupBox.setEnabled(False)
        self.macroInformation_GroupBox.setGeometry(QtCore.QRect(410, 10, 571, 211))
        self.macroInformation_GroupBox.setObjectName("macroInformation_GroupBox")
        self.macroInformation_TextEdit = QtWidgets.QTextEdit(self.macroInformation_GroupBox)
        self.macroInformation_TextEdit.setGeometry(QtCore.QRect(170, 20, 391, 181))
        self.macroInformation_TextEdit.setReadOnly(True)
        self.macroInformation_TextEdit.setObjectName("macroInformation_TextEdit")
        self.macroDelete_Button = QtWidgets.QPushButton(self.macroInformation_GroupBox)
        self.macroDelete_Button.setGeometry(QtCore.QRect(10, 170, 151, 30))
        self.macroDelete_Button.setObjectName("macroDelete_Button")
        self.macro_ListWidget = QtWidgets.QListWidget(self.macroInformation_GroupBox)
        self.macro_ListWidget.setGeometry(QtCore.QRect(10, 20, 151, 141))
        self.macro_ListWidget.setObjectName("macro_ListWidget")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Macro"))
        self.fileLoad_GroupBox.setTitle(_translate("Dialog", "File Load"))
        self.baseModelDataFile_Label.setText(_translate("Dialog", "Base Model File"))
        self.baseModelDataFileBroswer_Button.setText(_translate("Dialog", "Broswer..."))
        self.baseModelDataFileLoad_Button.setText(_translate("Dialog", "Load"))
        self.groupBox_.setTitle(_translate("Dialog", "Modify Factor"))
        self.modifyFactorDelete_Button.setText(_translate("Dialog", "Delete"))
        self.macroSize_Label.setText(_translate("Dialog", "Macro Size"))
        self.macroAdd_Button.setText(_translate("Dialog", "Macro Add"))
        self.layerSize_Label.setText(_translate("Dialog", "Layer"))
        self.label_4.setText(_translate("Dialog", "Step"))
        self.label_3.setText(_translate("Dialog", "to"))
        self.layerSizeAdd_Button.setText(_translate("Dialog", "Add"))
        self.layerSize_Label_2.setText(_translate("Dialog", "Range"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Layer Size"))
        self.regularMultiLayerSizeTo_Label.setText(_translate("Dialog", "to"))
        self.regularMultiLayerSizeRange_Label.setText(_translate("Dialog", "Range"))
        self.regularMultiLayerSizeStep_Label.setText(_translate("Dialog", "Step"))
        self.regularMultiLayerSizeLayerPrefix_Label.setText(_translate("Dialog", "Layer Prefix"))
        self.regularMultiLayerSizeMaxSuffix_Label.setText(_translate("Dialog", "Max Suffix"))
        self.regularMultiLayerSizeAdd_Button.setText(_translate("Dialog", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "Multi Layer Size (Regular)"))
        self.irregularMultiLayerSizeLayer_Label.setText(_translate("Dialog", "Layers"))
        self.irregularMultiLayerSizeTo_Label.setText(_translate("Dialog", "to"))
        self.irregularMultiLayerSizeStep_Label.setText(_translate("Dialog", "Step"))
        self.irregularMultiLayerSizeRange_LineEdit.setText(_translate("Dialog", "Range"))
        self.irregularMultiLayerSizeAdd_Button.setText(_translate("Dialog", "Add"))
        self.irregularMultiLayerSizeNotice_Label.setText(_translate("Dialog", "※ Use \'Space\' between layer names"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Dialog", "Multi Layer Size(Irregular)"))
        self.label_5.setText(_translate("Dialog", "to"))
        self.label_6.setText(_translate("Dialog", "Step"))
        self.learningRateAdd_Button.setText(_translate("Dialog", "Add"))
        self.layerSize_Label_3.setText(_translate("Dialog", "Range"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Learning Rate"))
        self.label_7.setText(_translate("Dialog", "to"))
        self.initialWeightSDAdd_Button.setText(_translate("Dialog", "Add"))
        self.label_8.setText(_translate("Dialog", "Step"))
        self.layerSize_Label_4.setText(_translate("Dialog", "Range"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Initial Weight SD"))
        self.layerDamageSDAdd_Button.setText(_translate("Dialog", "Add"))
        self.label_11.setText(_translate("Dialog", "to"))
        self.layerDamageSDOn_CheckBox.setText(_translate("Dialog", "Add \'On\'"))
        self.label_12.setText(_translate("Dialog", "Step"))
        self.layerDamageSDOff_CheckBox.setText(_translate("Dialog", "Add \'Off\'"))
        self.layerSize_Label_5.setText(_translate("Dialog", "Range"))
        self.layerSize_Label_6.setText(_translate("Dialog", "Layer"))
        self.layerSize_Label_10.setText(_translate("Dialog", "Process"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Layer Damage"))
        self.connectionDamageSDOff_CheckBox.setText(_translate("Dialog", "Add \'Off\'"))
        self.label_15.setText(_translate("Dialog", "to"))
        self.connectionDamageSDOn_CheckBox.setText(_translate("Dialog", "Add \'On\'"))
        self.connectionDamageSDAdd_Button.setText(_translate("Dialog", "Add"))
        self.label_16.setText(_translate("Dialog", "Step"))
        self.layerSize_Label_7.setText(_translate("Dialog", "Range"))
        self.layerSize_Label_8.setText(_translate("Dialog", "Layer"))
        self.layerSize_Label_9.setText(_translate("Dialog", "Process"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "Connection Damage"))
        self.baseModelStatus_GroupBox.setTitle(_translate("Dialog", "Base Model Status"))
        self.connection_Label.setText(_translate("Dialog", "Connection"))
        self.layer_Label.setText(_translate("Dialog", "Layer"))
        self.process_Label.setText(_translate("Dialog", "Process"))
        self.patternPack_Label.setText(_translate("Dialog", "Pattern Pack"))
        self.learningSetup_Label.setText(_translate("Dialog", "Learning Setup"))
        self.layer_Label_2.setText(_translate("Dialog", "Config Variables"))
        self.learning_Button.setText(_translate("Dialog", "Learning"))
        self.exit_Button.setText(_translate("Dialog", "Exit"))
        self.macroInformation_GroupBox.setTitle(_translate("Dialog", "Macro Information"))
        self.macroDelete_Button.setText(_translate("Dialog", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

