# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LearningSetup.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 705)
        Dialog.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.trainingPatternMatching_GroupBox = QtWidgets.QGroupBox(Dialog)
        self.trainingPatternMatching_GroupBox.setEnabled(True)
        self.trainingPatternMatching_GroupBox.setGeometry(QtCore.QRect(5, 155, 490, 511))
        self.trainingPatternMatching_GroupBox.setObjectName("trainingPatternMatching_GroupBox")
        self.trainingPatternPack_Label = QtWidgets.QLabel(self.trainingPatternMatching_GroupBox)
        self.trainingPatternPack_Label.setGeometry(QtCore.QRect(10, 164, 61, 16))
        self.trainingPatternPack_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.trainingPatternPack_Label.setObjectName("trainingPatternPack_Label")
        self.trainingProcess_Label = QtWidgets.QLabel(self.trainingPatternMatching_GroupBox)
        self.trainingProcess_Label.setGeometry(QtCore.QRect(250, 164, 61, 16))
        self.trainingProcess_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.trainingProcess_Label.setObjectName("trainingProcess_Label")
        self.trainingPatternToOrderInformation_Label = QtWidgets.QLabel(self.trainingPatternMatching_GroupBox)
        self.trainingPatternToOrderInformation_Label.setGeometry(QtCore.QRect(10, 220, 160, 16))
        self.trainingPatternToOrderInformation_Label.setObjectName("trainingPatternToOrderInformation_Label")
        self.trainingPattern_Label = QtWidgets.QLabel(self.trainingPatternMatching_GroupBox)
        self.trainingPattern_Label.setGeometry(QtCore.QRect(250, 250, 60, 13))
        self.trainingPattern_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.trainingPattern_Label.setObjectName("trainingPattern_Label")
        self.trainingOrder_Label = QtWidgets.QLabel(self.trainingPatternMatching_GroupBox)
        self.trainingOrder_Label.setGeometry(QtCore.QRect(250, 280, 60, 13))
        self.trainingOrder_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.trainingOrder_Label.setObjectName("trainingOrder_Label")
        self.trainingPatternPack_ComboBox = QtWidgets.QComboBox(self.trainingPatternMatching_GroupBox)
        self.trainingPatternPack_ComboBox.setEnabled(False)
        self.trainingPatternPack_ComboBox.setGeometry(QtCore.QRect(80, 160, 160, 22))
        self.trainingPatternPack_ComboBox.setObjectName("trainingPatternPack_ComboBox")
        self.trainingProcess_ComboBox = QtWidgets.QComboBox(self.trainingPatternMatching_GroupBox)
        self.trainingProcess_ComboBox.setEnabled(False)
        self.trainingProcess_ComboBox.setGeometry(QtCore.QRect(320, 160, 160, 22))
        self.trainingProcess_ComboBox.setObjectName("trainingProcess_ComboBox")
        self.trainingPattern_ComboBox = QtWidgets.QComboBox(self.trainingPatternMatching_GroupBox)
        self.trainingPattern_ComboBox.setEnabled(False)
        self.trainingPattern_ComboBox.setGeometry(QtCore.QRect(320, 246, 160, 22))
        self.trainingPattern_ComboBox.setObjectName("trainingPattern_ComboBox")
        self.trainingOrder_ComboBox = QtWidgets.QComboBox(self.trainingPatternMatching_GroupBox)
        self.trainingOrder_ComboBox.setEnabled(False)
        self.trainingOrder_ComboBox.setGeometry(QtCore.QRect(320, 276, 160, 22))
        self.trainingOrder_ComboBox.setObjectName("trainingOrder_ComboBox")
        self.trainingPatternToOrderAssign_Button = QtWidgets.QPushButton(self.trainingPatternMatching_GroupBox)
        self.trainingPatternToOrderAssign_Button.setEnabled(False)
        self.trainingPatternToOrderAssign_Button.setGeometry(QtCore.QRect(400, 310, 81, 30))
        self.trainingPatternToOrderAssign_Button.setObjectName("trainingPatternToOrderAssign_Button")
        self.trainingPatternMatchingDelete_Button = QtWidgets.QPushButton(self.trainingPatternMatching_GroupBox)
        self.trainingPatternMatchingDelete_Button.setEnabled(False)
        self.trainingPatternMatchingDelete_Button.setGeometry(QtCore.QRect(40, 120, 190, 30))
        self.trainingPatternMatchingDelete_Button.setObjectName("trainingPatternMatchingDelete_Button")
        self.trainingPatternMatchingDown_Button = QtWidgets.QPushButton(self.trainingPatternMatching_GroupBox)
        self.trainingPatternMatchingDown_Button.setEnabled(False)
        self.trainingPatternMatchingDown_Button.setGeometry(QtCore.QRect(10, 120, 30, 30))
        self.trainingPatternMatchingDown_Button.setObjectName("trainingPatternMatchingDown_Button")
        self.trainingPatternMatchingUp_Button = QtWidgets.QPushButton(self.trainingPatternMatching_GroupBox)
        self.trainingPatternMatchingUp_Button.setEnabled(False)
        self.trainingPatternMatchingUp_Button.setGeometry(QtCore.QRect(230, 120, 30, 30))
        self.trainingPatternMatchingUp_Button.setObjectName("trainingPatternMatchingUp_Button")
        self.trainingPatternMatchingMaking_Button = QtWidgets.QPushButton(self.trainingPatternMatching_GroupBox)
        self.trainingPatternMatchingMaking_Button.setEnabled(False)
        self.trainingPatternMatchingMaking_Button.setGeometry(QtCore.QRect(290, 40, 191, 30))
        self.trainingPatternMatchingMaking_Button.setObjectName("trainingPatternMatchingMaking_Button")
        self.trainingPatternToOrderDelete_Button = QtWidgets.QPushButton(self.trainingPatternMatching_GroupBox)
        self.trainingPatternToOrderDelete_Button.setEnabled(False)
        self.trainingPatternToOrderDelete_Button.setGeometry(QtCore.QRect(10, 410, 250, 30))
        self.trainingPatternToOrderDelete_Button.setObjectName("trainingPatternToOrderDelete_Button")
        self.trainingAutoAssign_Button = QtWidgets.QPushButton(self.trainingPatternMatching_GroupBox)
        self.trainingAutoAssign_Button.setEnabled(False)
        self.trainingAutoAssign_Button.setGeometry(QtCore.QRect(400, 190, 81, 30))
        self.trainingAutoAssign_Button.setObjectName("trainingAutoAssign_Button")
        self.trainingPatternMatching_Label = QtWidgets.QLabel(self.trainingPatternMatching_GroupBox)
        self.trainingPatternMatching_Label.setGeometry(QtCore.QRect(10, 20, 141, 16))
        self.trainingPatternMatching_Label.setObjectName("trainingPatternMatching_Label")
        self.trainingPatternMatchingEnd_Button = QtWidgets.QPushButton(self.trainingPatternMatching_GroupBox)
        self.trainingPatternMatchingEnd_Button.setEnabled(False)
        self.trainingPatternMatchingEnd_Button.setGeometry(QtCore.QRect(290, 80, 191, 30))
        self.trainingPatternMatchingEnd_Button.setObjectName("trainingPatternMatchingEnd_Button")
        self.trainingPatternMatching_ListWidget = QtWidgets.QListWidget(self.trainingPatternMatching_GroupBox)
        self.trainingPatternMatching_ListWidget.setGeometry(QtCore.QRect(10, 40, 250, 71))
        self.trainingPatternMatching_ListWidget.setObjectName("trainingPatternMatching_ListWidget")
        self.trainingPatternToOrderInformation_ListWidget = QtWidgets.QListWidget(self.trainingPatternMatching_GroupBox)
        self.trainingPatternToOrderInformation_ListWidget.setGeometry(QtCore.QRect(10, 240, 250, 161))
        self.trainingPatternToOrderInformation_ListWidget.setObjectName("trainingPatternToOrderInformation_ListWidget")
        self.learningSetup_GroupBox = QtWidgets.QGroupBox(Dialog)
        self.learningSetup_GroupBox.setGeometry(QtCore.QRect(5, 10, 491, 141))
        self.learningSetup_GroupBox.setObjectName("learningSetup_GroupBox")
        self.learningSetupDelete_Button = QtWidgets.QPushButton(self.learningSetup_GroupBox)
        self.learningSetupDelete_Button.setGeometry(QtCore.QRect(40, 100, 171, 30))
        self.learningSetupDelete_Button.setObjectName("learningSetupDelete_Button")
        self.learningSetupDown_Button = QtWidgets.QPushButton(self.learningSetup_GroupBox)
        self.learningSetupDown_Button.setGeometry(QtCore.QRect(10, 100, 30, 30))
        self.learningSetupDown_Button.setObjectName("learningSetupDown_Button")
        self.learningSetupUp_Button = QtWidgets.QPushButton(self.learningSetup_GroupBox)
        self.learningSetupUp_Button.setGeometry(QtCore.QRect(210, 100, 30, 30))
        self.learningSetupUp_Button.setObjectName("learningSetupUp_Button")
        self.learningSetupMaking_Button = QtWidgets.QPushButton(self.learningSetup_GroupBox)
        self.learningSetupMaking_Button.setGeometry(QtCore.QRect(260, 65, 100, 30))
        self.learningSetupMaking_Button.setObjectName("learningSetupMaking_Button")
        self.learningSetupEnd_Button = QtWidgets.QPushButton(self.learningSetup_GroupBox)
        self.learningSetupEnd_Button.setEnabled(False)
        self.learningSetupEnd_Button.setGeometry(QtCore.QRect(320, 100, 100, 30))
        self.learningSetupEnd_Button.setObjectName("learningSetupEnd_Button")
        self.learningSetupModify_Button = QtWidgets.QPushButton(self.learningSetup_GroupBox)
        self.learningSetupModify_Button.setGeometry(QtCore.QRect(380, 65, 100, 30))
        self.learningSetupModify_Button.setObjectName("learningSetupModify_Button")
        self.learningSetupName_Label = QtWidgets.QLabel(self.learningSetup_GroupBox)
        self.learningSetupName_Label.setGeometry(QtCore.QRect(260, 20, 101, 16))
        self.learningSetupName_Label.setObjectName("learningSetupName_Label")
        self.learningSetupName_LineEdit = QtWidgets.QLineEdit(self.learningSetup_GroupBox)
        self.learningSetupName_LineEdit.setGeometry(QtCore.QRect(260, 40, 221, 20))
        self.learningSetupName_LineEdit.setObjectName("learningSetupName_LineEdit")
        self.learningSetup_ListWidget = QtWidgets.QListWidget(self.learningSetup_GroupBox)
        self.learningSetup_ListWidget.setGeometry(QtCore.QRect(10, 20, 231, 71))
        self.learningSetup_ListWidget.setObjectName("learningSetup_ListWidget")
        self.trainingAndTestMethod_GroupBox = QtWidgets.QGroupBox(Dialog)
        self.trainingAndTestMethod_GroupBox.setEnabled(True)
        self.trainingAndTestMethod_GroupBox.setGeometry(QtCore.QRect(505, 10, 491, 141))
        self.trainingAndTestMethod_GroupBox.setObjectName("trainingAndTestMethod_GroupBox")
        self.shufflingMethod_ComboBox = QtWidgets.QComboBox(self.trainingAndTestMethod_GroupBox)
        self.shufflingMethod_ComboBox.setEnabled(False)
        self.shufflingMethod_ComboBox.setGeometry(QtCore.QRect(110, 110, 260, 22))
        self.shufflingMethod_ComboBox.setObjectName("shufflingMethod_ComboBox")
        self.shufflingMethod_ComboBox.addItem("")
        self.shufflingMethod_ComboBox.addItem("")
        self.shufflingMethod_ComboBox.addItem("")
        self.shufflingMethod_ComboBox.addItem("")
        self.shufflingMethod_ComboBox.addItem("")
        self.shufflingMethod_Label = QtWidgets.QLabel(self.trainingAndTestMethod_GroupBox)
        self.shufflingMethod_Label.setGeometry(QtCore.QRect(10, 114, 90, 13))
        self.shufflingMethod_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.shufflingMethod_Label.setObjectName("shufflingMethod_Label")
        self.testTiming_Label = QtWidgets.QLabel(self.trainingAndTestMethod_GroupBox)
        self.testTiming_Label.setGeometry(QtCore.QRect(10, 54, 90, 13))
        self.testTiming_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.testTiming_Label.setObjectName("testTiming_Label")
        self.trainingEpoch_Label = QtWidgets.QLabel(self.trainingAndTestMethod_GroupBox)
        self.trainingEpoch_Label.setGeometry(QtCore.QRect(10, 24, 90, 13))
        self.trainingEpoch_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.trainingEpoch_Label.setObjectName("trainingEpoch_Label")
        self.miniBatchSize_Label = QtWidgets.QLabel(self.trainingAndTestMethod_GroupBox)
        self.miniBatchSize_Label.setGeometry(QtCore.QRect(10, 84, 90, 13))
        self.miniBatchSize_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.miniBatchSize_Label.setObjectName("miniBatchSize_Label")
        self.trainingEpoch_LineEdit = QtWidgets.QLineEdit(self.trainingAndTestMethod_GroupBox)
        self.trainingEpoch_LineEdit.setEnabled(False)
        self.trainingEpoch_LineEdit.setGeometry(QtCore.QRect(110, 20, 120, 20))
        self.trainingEpoch_LineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.trainingEpoch_LineEdit.setText("")
        self.trainingEpoch_LineEdit.setFrame(True)
        self.trainingEpoch_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.trainingEpoch_LineEdit.setReadOnly(False)
        self.trainingEpoch_LineEdit.setObjectName("trainingEpoch_LineEdit")
        self.testTiming_LineEdit = QtWidgets.QLineEdit(self.trainingAndTestMethod_GroupBox)
        self.testTiming_LineEdit.setEnabled(False)
        self.testTiming_LineEdit.setGeometry(QtCore.QRect(110, 50, 120, 20))
        self.testTiming_LineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.testTiming_LineEdit.setText("")
        self.testTiming_LineEdit.setFrame(True)
        self.testTiming_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.testTiming_LineEdit.setReadOnly(False)
        self.testTiming_LineEdit.setObjectName("testTiming_LineEdit")
        self.miniBatchSize_LineEdit = QtWidgets.QLineEdit(self.trainingAndTestMethod_GroupBox)
        self.miniBatchSize_LineEdit.setEnabled(False)
        self.miniBatchSize_LineEdit.setGeometry(QtCore.QRect(110, 80, 120, 20))
        self.miniBatchSize_LineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.miniBatchSize_LineEdit.setText("")
        self.miniBatchSize_LineEdit.setFrame(True)
        self.miniBatchSize_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.miniBatchSize_LineEdit.setReadOnly(False)
        self.miniBatchSize_LineEdit.setObjectName("miniBatchSize_LineEdit")
        self.load_Button = QtWidgets.QPushButton(Dialog)
        self.load_Button.setGeometry(QtCore.QRect(420, 670, 160, 30))
        self.load_Button.setObjectName("load_Button")
        self.save_Button = QtWidgets.QPushButton(Dialog)
        self.save_Button.setGeometry(QtCore.QRect(200, 670, 160, 30))
        self.save_Button.setObjectName("save_Button")
        self.exit_Button = QtWidgets.QPushButton(Dialog)
        self.exit_Button.setGeometry(QtCore.QRect(640, 670, 160, 30))
        self.exit_Button.setObjectName("exit_Button")
        self.testPatternMatching_GroupBox = QtWidgets.QGroupBox(Dialog)
        self.testPatternMatching_GroupBox.setEnabled(True)
        self.testPatternMatching_GroupBox.setGeometry(QtCore.QRect(505, 155, 490, 511))
        self.testPatternMatching_GroupBox.setObjectName("testPatternMatching_GroupBox")
        self.testPatternPack_Label = QtWidgets.QLabel(self.testPatternMatching_GroupBox)
        self.testPatternPack_Label.setGeometry(QtCore.QRect(10, 164, 61, 16))
        self.testPatternPack_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.testPatternPack_Label.setObjectName("testPatternPack_Label")
        self.testProcess_Label = QtWidgets.QLabel(self.testPatternMatching_GroupBox)
        self.testProcess_Label.setGeometry(QtCore.QRect(250, 164, 61, 16))
        self.testProcess_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.testProcess_Label.setObjectName("testProcess_Label")
        self.testPatternToOrderInformation_Label = QtWidgets.QLabel(self.testPatternMatching_GroupBox)
        self.testPatternToOrderInformation_Label.setGeometry(QtCore.QRect(10, 220, 160, 16))
        self.testPatternToOrderInformation_Label.setObjectName("testPatternToOrderInformation_Label")
        self.testPattern_Label = QtWidgets.QLabel(self.testPatternMatching_GroupBox)
        self.testPattern_Label.setGeometry(QtCore.QRect(250, 250, 60, 13))
        self.testPattern_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.testPattern_Label.setObjectName("testPattern_Label")
        self.testOrder_Label = QtWidgets.QLabel(self.testPatternMatching_GroupBox)
        self.testOrder_Label.setGeometry(QtCore.QRect(250, 280, 60, 13))
        self.testOrder_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.testOrder_Label.setObjectName("testOrder_Label")
        self.testPatternPack_ComboBox = QtWidgets.QComboBox(self.testPatternMatching_GroupBox)
        self.testPatternPack_ComboBox.setEnabled(False)
        self.testPatternPack_ComboBox.setGeometry(QtCore.QRect(80, 160, 160, 22))
        self.testPatternPack_ComboBox.setObjectName("testPatternPack_ComboBox")
        self.testProcess_ComboBox = QtWidgets.QComboBox(self.testPatternMatching_GroupBox)
        self.testProcess_ComboBox.setEnabled(False)
        self.testProcess_ComboBox.setGeometry(QtCore.QRect(320, 160, 160, 22))
        self.testProcess_ComboBox.setObjectName("testProcess_ComboBox")
        self.testPattern_ComboBox = QtWidgets.QComboBox(self.testPatternMatching_GroupBox)
        self.testPattern_ComboBox.setEnabled(False)
        self.testPattern_ComboBox.setGeometry(QtCore.QRect(320, 246, 160, 22))
        self.testPattern_ComboBox.setObjectName("testPattern_ComboBox")
        self.testOrder_ComboBox = QtWidgets.QComboBox(self.testPatternMatching_GroupBox)
        self.testOrder_ComboBox.setEnabled(False)
        self.testOrder_ComboBox.setGeometry(QtCore.QRect(320, 276, 160, 22))
        self.testOrder_ComboBox.setObjectName("testOrder_ComboBox")
        self.testPatternToOrderAssign_Button = QtWidgets.QPushButton(self.testPatternMatching_GroupBox)
        self.testPatternToOrderAssign_Button.setEnabled(False)
        self.testPatternToOrderAssign_Button.setGeometry(QtCore.QRect(400, 310, 81, 30))
        self.testPatternToOrderAssign_Button.setObjectName("testPatternToOrderAssign_Button")
        self.testPatternMatchingDelete_Button = QtWidgets.QPushButton(self.testPatternMatching_GroupBox)
        self.testPatternMatchingDelete_Button.setEnabled(False)
        self.testPatternMatchingDelete_Button.setGeometry(QtCore.QRect(10, 120, 250, 30))
        self.testPatternMatchingDelete_Button.setObjectName("testPatternMatchingDelete_Button")
        self.testPatternMatchingMaking_Button = QtWidgets.QPushButton(self.testPatternMatching_GroupBox)
        self.testPatternMatchingMaking_Button.setEnabled(False)
        self.testPatternMatchingMaking_Button.setGeometry(QtCore.QRect(290, 40, 191, 30))
        self.testPatternMatchingMaking_Button.setObjectName("testPatternMatchingMaking_Button")
        self.testPatternToOrderDelete_Button = QtWidgets.QPushButton(self.testPatternMatching_GroupBox)
        self.testPatternToOrderDelete_Button.setEnabled(False)
        self.testPatternToOrderDelete_Button.setGeometry(QtCore.QRect(10, 310, 250, 30))
        self.testPatternToOrderDelete_Button.setObjectName("testPatternToOrderDelete_Button")
        self.testAutoAssign_Button = QtWidgets.QPushButton(self.testPatternMatching_GroupBox)
        self.testAutoAssign_Button.setEnabled(False)
        self.testAutoAssign_Button.setGeometry(QtCore.QRect(400, 190, 81, 30))
        self.testAutoAssign_Button.setObjectName("testAutoAssign_Button")
        self.testPatternMatching_Label = QtWidgets.QLabel(self.testPatternMatching_GroupBox)
        self.testPatternMatching_Label.setGeometry(QtCore.QRect(10, 20, 141, 16))
        self.testPatternMatching_Label.setObjectName("testPatternMatching_Label")
        self.testPatternMatchingEnd_Button = QtWidgets.QPushButton(self.testPatternMatching_GroupBox)
        self.testPatternMatchingEnd_Button.setEnabled(False)
        self.testPatternMatchingEnd_Button.setGeometry(QtCore.QRect(290, 80, 191, 30))
        self.testPatternMatchingEnd_Button.setObjectName("testPatternMatchingEnd_Button")
        self.testPatternMatching_ListWidget = QtWidgets.QListWidget(self.testPatternMatching_GroupBox)
        self.testPatternMatching_ListWidget.setGeometry(QtCore.QRect(10, 40, 250, 71))
        self.testPatternMatching_ListWidget.setObjectName("testPatternMatching_ListWidget")
        self.testPatternToOrderInformation_ListWidget = QtWidgets.QListWidget(self.testPatternMatching_GroupBox)
        self.testPatternToOrderInformation_ListWidget.setGeometry(QtCore.QRect(10, 240, 250, 61))
        self.testPatternToOrderInformation_ListWidget.setObjectName("testPatternToOrderInformation_ListWidget")
        self.extractDataDelete_Button = QtWidgets.QPushButton(self.testPatternMatching_GroupBox)
        self.extractDataDelete_Button.setEnabled(False)
        self.extractDataDelete_Button.setGeometry(QtCore.QRect(10, 470, 250, 30))
        self.extractDataDelete_Button.setObjectName("extractDataDelete_Button")
        self.extractData_ListWidget = QtWidgets.QListWidget(self.testPatternMatching_GroupBox)
        self.extractData_ListWidget.setGeometry(QtCore.QRect(10, 370, 250, 91))
        self.extractData_ListWidget.setObjectName("extractData_ListWidget")
        self.extractData_Label = QtWidgets.QLabel(self.testPatternMatching_GroupBox)
        self.extractData_Label.setGeometry(QtCore.QRect(10, 350, 160, 16))
        self.extractData_Label.setObjectName("extractData_Label")
        self.extractDataAssign_Button = QtWidgets.QPushButton(self.testPatternMatching_GroupBox)
        self.extractDataAssign_Button.setEnabled(False)
        self.extractDataAssign_Button.setGeometry(QtCore.QRect(400, 470, 81, 30))
        self.extractDataAssign_Button.setObjectName("extractDataAssign_Button")
        self.extractDataOrder_ComboBox = QtWidgets.QComboBox(self.testPatternMatching_GroupBox)
        self.extractDataOrder_ComboBox.setEnabled(False)
        self.extractDataOrder_ComboBox.setGeometry(QtCore.QRect(320, 406, 160, 22))
        self.extractDataOrder_ComboBox.setObjectName("extractDataOrder_ComboBox")
        self.extractDataOrder_Label = QtWidgets.QLabel(self.testPatternMatching_GroupBox)
        self.extractDataOrder_Label.setGeometry(QtCore.QRect(250, 410, 60, 13))
        self.extractDataOrder_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.extractDataOrder_Label.setObjectName("extractDataOrder_Label")
        self.extractDataPattern_ComboBox = QtWidgets.QComboBox(self.testPatternMatching_GroupBox)
        self.extractDataPattern_ComboBox.setEnabled(False)
        self.extractDataPattern_ComboBox.setGeometry(QtCore.QRect(320, 376, 160, 22))
        self.extractDataPattern_ComboBox.setObjectName("extractDataPattern_ComboBox")
        self.extractDataPattern_Label = QtWidgets.QLabel(self.testPatternMatching_GroupBox)
        self.extractDataPattern_Label.setGeometry(QtCore.QRect(250, 380, 60, 13))
        self.extractDataPattern_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.extractDataPattern_Label.setObjectName("extractDataPattern_Label")
        self.extractDataType_ComboBox = QtWidgets.QComboBox(self.testPatternMatching_GroupBox)
        self.extractDataType_ComboBox.setEnabled(False)
        self.extractDataType_ComboBox.setGeometry(QtCore.QRect(320, 440, 160, 22))
        self.extractDataType_ComboBox.setObjectName("extractDataType_ComboBox")
        self.extractDataType_ComboBox.addItem("")
        self.extractDataType_ComboBox.addItem("")
        self.extractDataType_ComboBox.addItem("")
        self.extractDataType_ComboBox.addItem("")
        self.extractDataType_Label = QtWidgets.QLabel(self.testPatternMatching_GroupBox)
        self.extractDataType_Label.setGeometry(QtCore.QRect(250, 444, 60, 13))
        self.extractDataType_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.extractDataType_Label.setObjectName("extractDataType_Label")
        self.extractDataAutoAssign_Button = QtWidgets.QPushButton(self.testPatternMatching_GroupBox)
        self.extractDataAutoAssign_Button.setEnabled(False)
        self.extractDataAutoAssign_Button.setGeometry(QtCore.QRect(300, 470, 81, 30))
        self.extractDataAutoAssign_Button.setObjectName("extractDataAutoAssign_Button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Learning Setup"))
        self.trainingPatternMatching_GroupBox.setTitle(_translate("Dialog", "Training Pattern Matching"))
        self.trainingPatternPack_Label.setText(_translate("Dialog", "Pattern Pack"))
        self.trainingProcess_Label.setText(_translate("Dialog", "Process"))
        self.trainingPatternToOrderInformation_Label.setText(_translate("Dialog", "Order ← Pattern Information"))
        self.trainingPattern_Label.setText(_translate("Dialog", "Pattern"))
        self.trainingOrder_Label.setText(_translate("Dialog", "Order"))
        self.trainingPatternToOrderAssign_Button.setText(_translate("Dialog", "Assign"))
        self.trainingPatternMatchingDelete_Button.setText(_translate("Dialog", "Delete"))
        self.trainingPatternMatchingDown_Button.setText(_translate("Dialog", "▼"))
        self.trainingPatternMatchingUp_Button.setText(_translate("Dialog", "▲"))
        self.trainingPatternMatchingMaking_Button.setText(_translate("Dialog", "Making"))
        self.trainingPatternToOrderDelete_Button.setText(_translate("Dialog", "Delete"))
        self.trainingAutoAssign_Button.setText(_translate("Dialog", "Auto Assign"))
        self.trainingPatternMatching_Label.setText(_translate("Dialog", "Pattern Matching Information"))
        self.trainingPatternMatchingEnd_Button.setText(_translate("Dialog", "End"))
        self.learningSetup_GroupBox.setTitle(_translate("Dialog", "Learning Setup"))
        self.learningSetupDelete_Button.setText(_translate("Dialog", "Delete"))
        self.learningSetupDown_Button.setText(_translate("Dialog", "▼"))
        self.learningSetupUp_Button.setText(_translate("Dialog", "▲"))
        self.learningSetupMaking_Button.setText(_translate("Dialog", "Making"))
        self.learningSetupEnd_Button.setText(_translate("Dialog", "End"))
        self.learningSetupModify_Button.setText(_translate("Dialog", "Modify"))
        self.learningSetupName_Label.setText(_translate("Dialog", "Learning Setup Name"))
        self.trainingAndTestMethod_GroupBox.setTitle(_translate("Dialog", "Training && Test Method"))
        self.shufflingMethod_ComboBox.setItemText(0, _translate("Dialog", "Random all"))
        self.shufflingMethod_ComboBox.setItemText(1, _translate("Dialog", "Matching: Random, Pattern: Random"))
        self.shufflingMethod_ComboBox.setItemText(2, _translate("Dialog", "Matching: Sequence, Pattern: Random"))
        self.shufflingMethod_ComboBox.setItemText(3, _translate("Dialog", "Matching: Random, Pattern: Sequence"))
        self.shufflingMethod_ComboBox.setItemText(4, _translate("Dialog", "Matching: Sequence, Pattern: Sequence"))
        self.shufflingMethod_Label.setText(_translate("Dialog", "Shuffleing Method"))
        self.testTiming_Label.setText(_translate("Dialog", "Test Timing"))
        self.trainingEpoch_Label.setText(_translate("Dialog", "Training Epoch"))
        self.miniBatchSize_Label.setText(_translate("Dialog", "Mini-Batch Size"))
        self.load_Button.setText(_translate("Dialog", "Learning Setup Load"))
        self.save_Button.setText(_translate("Dialog", "Learning Setup Save"))
        self.exit_Button.setText(_translate("Dialog", "Exit"))
        self.testPatternMatching_GroupBox.setTitle(_translate("Dialog", "Test Pattern Matching"))
        self.testPatternPack_Label.setText(_translate("Dialog", "Pattern Pack"))
        self.testProcess_Label.setText(_translate("Dialog", "Process"))
        self.testPatternToOrderInformation_Label.setText(_translate("Dialog", "Order ← Pattern Information"))
        self.testPattern_Label.setText(_translate("Dialog", "Pattern"))
        self.testOrder_Label.setText(_translate("Dialog", "Order"))
        self.testPatternToOrderAssign_Button.setText(_translate("Dialog", "Assign"))
        self.testPatternMatchingDelete_Button.setText(_translate("Dialog", "Delete"))
        self.testPatternMatchingMaking_Button.setText(_translate("Dialog", "Making"))
        self.testPatternToOrderDelete_Button.setText(_translate("Dialog", "Delete"))
        self.testAutoAssign_Button.setText(_translate("Dialog", "Auto Assign"))
        self.testPatternMatching_Label.setText(_translate("Dialog", "Pattern Matching Information"))
        self.testPatternMatchingEnd_Button.setText(_translate("Dialog", "End"))
        self.extractDataDelete_Button.setText(_translate("Dialog", "Delete"))
        self.extractData_Label.setText(_translate("Dialog", "Extract Data from Activation"))
        self.extractDataAssign_Button.setText(_translate("Dialog", "Assign"))
        self.extractDataOrder_Label.setText(_translate("Dialog", "Order"))
        self.extractDataPattern_Label.setText(_translate("Dialog", "Pattern"))
        self.extractDataType_ComboBox.setItemText(0, _translate("Dialog", "Raw Activation"))
        self.extractDataType_ComboBox.setItemText(1, _translate("Dialog", "Mean Squared Error"))
        self.extractDataType_ComboBox.setItemText(2, _translate("Dialog", "Cross Entropy"))
        self.extractDataType_ComboBox.setItemText(3, _translate("Dialog", "Semantic Stress"))
        self.extractDataType_Label.setText(_translate("Dialog", "Ext. Type"))
        self.extractDataAutoAssign_Button.setText(_translate("Dialog", "Auto Assign"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

