# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProcessSetup.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(954, 824)
        self.process_GroupBox = QtWidgets.QGroupBox(Dialog)
        self.process_GroupBox.setGeometry(QtCore.QRect(10, 10, 391, 171))
        self.process_GroupBox.setObjectName("process_GroupBox")
        self.processDelete_Button = QtWidgets.QPushButton(self.process_GroupBox)
        self.processDelete_Button.setGeometry(QtCore.QRect(10, 130, 181, 31))
        self.processDelete_Button.setObjectName("processDelete_Button")
        self.processName_Label = QtWidgets.QLabel(self.process_GroupBox)
        self.processName_Label.setGeometry(QtCore.QRect(200, 20, 71, 16))
        self.processName_Label.setObjectName("processName_Label")
        self.processName_LineEdit = QtWidgets.QLineEdit(self.process_GroupBox)
        self.processName_LineEdit.setGeometry(QtCore.QRect(200, 40, 181, 20))
        self.processName_LineEdit.setObjectName("processName_LineEdit")
        self.processMaking_Button = QtWidgets.QPushButton(self.process_GroupBox)
        self.processMaking_Button.setGeometry(QtCore.QRect(200, 90, 75, 30))
        self.processMaking_Button.setObjectName("processMaking_Button")
        self.processModify_Button = QtWidgets.QPushButton(self.process_GroupBox)
        self.processModify_Button.setGeometry(QtCore.QRect(310, 90, 75, 30))
        self.processModify_Button.setObjectName("processModify_Button")
        self.processEnd_Button = QtWidgets.QPushButton(self.process_GroupBox)
        self.processEnd_Button.setEnabled(False)
        self.processEnd_Button.setGeometry(QtCore.QRect(255, 130, 75, 30))
        self.processEnd_Button.setObjectName("processEnd_Button")
        self.process_ListWidget = QtWidgets.QListWidget(self.process_GroupBox)
        self.process_ListWidget.setGeometry(QtCore.QRect(10, 20, 181, 100))
        self.process_ListWidget.setObjectName("process_ListWidget")
        self.layerControl_GroupBox = QtWidgets.QGroupBox(Dialog)
        self.layerControl_GroupBox.setGeometry(QtCore.QRect(440, 10, 251, 171))
        self.layerControl_GroupBox.setObjectName("layerControl_GroupBox")
        self.layerOn_Button = QtWidgets.QPushButton(self.layerControl_GroupBox)
        self.layerOn_Button.setEnabled(False)
        self.layerOn_Button.setGeometry(QtCore.QRect(10, 95, 110, 30))
        self.layerOn_Button.setObjectName("layerOn_Button")
        self.layerDamage_Button = QtWidgets.QPushButton(self.layerControl_GroupBox)
        self.layerDamage_Button.setEnabled(False)
        self.layerDamage_Button.setGeometry(QtCore.QRect(130, 130, 110, 30))
        self.layerDamage_Button.setObjectName("layerDamage_Button")
        self.layerOff_Button = QtWidgets.QPushButton(self.layerControl_GroupBox)
        self.layerOff_Button.setEnabled(False)
        self.layerOff_Button.setGeometry(QtCore.QRect(130, 95, 110, 30))
        self.layerOff_Button.setObjectName("layerOff_Button")
        self.layerDamageSD_LineEdit = QtWidgets.QLineEdit(self.layerControl_GroupBox)
        self.layerDamageSD_LineEdit.setEnabled(False)
        self.layerDamageSD_LineEdit.setGeometry(QtCore.QRect(39, 134, 81, 20))
        self.layerDamageSD_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layerDamageSD_LineEdit.setObjectName("layerDamageSD_LineEdit")
        self.layerDamageSD_Label = QtWidgets.QLabel(self.layerControl_GroupBox)
        self.layerDamageSD_Label.setGeometry(QtCore.QRect(15, 136, 21, 16))
        self.layerDamageSD_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.layerDamageSD_Label.setObjectName("layerDamageSD_Label")
        self.layerControl_ListWidget = QtWidgets.QListWidget(self.layerControl_GroupBox)
        self.layerControl_ListWidget.setGeometry(QtCore.QRect(10, 20, 231, 71))
        self.layerControl_ListWidget.setObjectName("layerControl_ListWidget")
        self.connectionControl_GroupBox = QtWidgets.QGroupBox(Dialog)
        self.connectionControl_GroupBox.setGeometry(QtCore.QRect(700, 10, 251, 171))
        self.connectionControl_GroupBox.setObjectName("connectionControl_GroupBox")
        self.connectionOn_Button = QtWidgets.QPushButton(self.connectionControl_GroupBox)
        self.connectionOn_Button.setEnabled(False)
        self.connectionOn_Button.setGeometry(QtCore.QRect(10, 95, 110, 30))
        self.connectionOn_Button.setObjectName("connectionOn_Button")
        self.connectionDamageSD_LineEdit = QtWidgets.QLineEdit(self.connectionControl_GroupBox)
        self.connectionDamageSD_LineEdit.setEnabled(False)
        self.connectionDamageSD_LineEdit.setGeometry(QtCore.QRect(39, 134, 81, 20))
        self.connectionDamageSD_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.connectionDamageSD_LineEdit.setObjectName("connectionDamageSD_LineEdit")
        self.connectionOff_Button = QtWidgets.QPushButton(self.connectionControl_GroupBox)
        self.connectionOff_Button.setEnabled(False)
        self.connectionOff_Button.setGeometry(QtCore.QRect(130, 95, 110, 30))
        self.connectionOff_Button.setObjectName("connectionOff_Button")
        self.connectionDamageSD_Label = QtWidgets.QLabel(self.connectionControl_GroupBox)
        self.connectionDamageSD_Label.setGeometry(QtCore.QRect(15, 136, 21, 16))
        self.connectionDamageSD_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.connectionDamageSD_Label.setObjectName("connectionDamageSD_Label")
        self.connectionDamage_Button = QtWidgets.QPushButton(self.connectionControl_GroupBox)
        self.connectionDamage_Button.setEnabled(False)
        self.connectionDamage_Button.setGeometry(QtCore.QRect(130, 130, 110, 30))
        self.connectionDamage_Button.setObjectName("connectionDamage_Button")
        self.connectionControl_ListWidget = QtWidgets.QListWidget(self.connectionControl_GroupBox)
        self.connectionControl_ListWidget.setGeometry(QtCore.QRect(10, 20, 231, 71))
        self.connectionControl_ListWidget.setObjectName("connectionControl_ListWidget")
        self.orderDown_Button = QtWidgets.QPushButton(Dialog)
        self.orderDown_Button.setEnabled(False)
        self.orderDown_Button.setGeometry(QtCore.QRect(10, 737, 30, 30))
        self.orderDown_Button.setObjectName("orderDown_Button")
        self.orderDelete_Button = QtWidgets.QPushButton(Dialog)
        self.orderDelete_Button.setEnabled(False)
        self.orderDelete_Button.setGeometry(QtCore.QRect(45, 737, 191, 30))
        self.orderDelete_Button.setObjectName("orderDelete_Button")
        self.orderUp_Button = QtWidgets.QPushButton(Dialog)
        self.orderUp_Button.setEnabled(False)
        self.orderUp_Button.setGeometry(QtCore.QRect(240, 737, 30, 30))
        self.orderUp_Button.setObjectName("orderUp_Button")
        self.order_TapWidget = QtWidgets.QTabWidget(Dialog)
        self.order_TapWidget.setEnabled(False)
        self.order_TapWidget.setGeometry(QtCore.QRect(280, 187, 671, 581))
        self.order_TapWidget.setObjectName("order_TapWidget")
        self.bp_Tap = QtWidgets.QWidget()
        self.bp_Tap.setObjectName("bp_Tap")
        self.bpInputLayer_Label = QtWidgets.QLabel(self.bp_Tap)
        self.bpInputLayer_Label.setGeometry(QtCore.QRect(20, 24, 47, 13))
        self.bpInputLayer_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bpInputLayer_Label.setObjectName("bpInputLayer_Label")
        self.bpHiddenLayer_Label = QtWidgets.QLabel(self.bp_Tap)
        self.bpHiddenLayer_Label.setGeometry(QtCore.QRect(20, 54, 47, 13))
        self.bpHiddenLayer_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bpHiddenLayer_Label.setObjectName("bpHiddenLayer_Label")
        self.bpOutputLayer_Label = QtWidgets.QLabel(self.bp_Tap)
        self.bpOutputLayer_Label.setGeometry(QtCore.QRect(20, 134, 47, 13))
        self.bpOutputLayer_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bpOutputLayer_Label.setObjectName("bpOutputLayer_Label")
        self.frame = QtWidgets.QFrame(self.bp_Tap)
        self.frame.setGeometry(QtCore.QRect(80, 160, 171, 41))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bpOutputTypeLinear_RadioButton = QtWidgets.QRadioButton(self.frame)
        self.bpOutputTypeLinear_RadioButton.setGeometry(QtCore.QRect(10, 0, 70, 17))
        self.bpOutputTypeLinear_RadioButton.setChecked(False)
        self.bpOutputTypeLinear_RadioButton.setObjectName("bpOutputTypeLinear_RadioButton")
        self.bpOutputTypeTanh_RadioButton = QtWidgets.QRadioButton(self.frame)
        self.bpOutputTypeTanh_RadioButton.setGeometry(QtCore.QRect(100, 20, 70, 17))
        self.bpOutputTypeTanh_RadioButton.setObjectName("bpOutputTypeTanh_RadioButton")
        self.bpOutputTypeSoftmax_RadioButton = QtWidgets.QRadioButton(self.frame)
        self.bpOutputTypeSoftmax_RadioButton.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.bpOutputTypeSoftmax_RadioButton.setObjectName("bpOutputTypeSoftmax_RadioButton")
        self.bpOutputTypeSigmoid_RadioButton = QtWidgets.QRadioButton(self.frame)
        self.bpOutputTypeSigmoid_RadioButton.setGeometry(QtCore.QRect(100, 0, 70, 17))
        self.bpOutputTypeSigmoid_RadioButton.setChecked(True)
        self.bpOutputTypeSigmoid_RadioButton.setObjectName("bpOutputTypeSigmoid_RadioButton")
        self.bpTrainingApply_Button = QtWidgets.QPushButton(self.bp_Tap)
        self.bpTrainingApply_Button.setGeometry(QtCore.QRect(40, 220, 100, 30))
        self.bpTrainingApply_Button.setObjectName("bpTrainingApply_Button")
        self.bpTestApply_Button = QtWidgets.QPushButton(self.bp_Tap)
        self.bpTestApply_Button.setGeometry(QtCore.QRect(150, 220, 100, 30))
        self.bpTestApply_Button.setObjectName("bpTestApply_Button")
        self.bpInputLayer_ComboBox = QtWidgets.QComboBox(self.bp_Tap)
        self.bpInputLayer_ComboBox.setGeometry(QtCore.QRect(80, 20, 170, 20))
        self.bpInputLayer_ComboBox.setObjectName("bpInputLayer_ComboBox")
        self.bpHiddenLayer_ComboBox = QtWidgets.QComboBox(self.bp_Tap)
        self.bpHiddenLayer_ComboBox.setGeometry(QtCore.QRect(80, 50, 170, 20))
        self.bpHiddenLayer_ComboBox.setObjectName("bpHiddenLayer_ComboBox")
        self.bpOutputLayer_ComboBox = QtWidgets.QComboBox(self.bp_Tap)
        self.bpOutputLayer_ComboBox.setGeometry(QtCore.QRect(80, 130, 170, 20))
        self.bpOutputLayer_ComboBox.setObjectName("bpOutputLayer_ComboBox")
        self.bpExampleGraph_Label = QtWidgets.QLabel(self.bp_Tap)
        self.bpExampleGraph_Label.setGeometry(QtCore.QRect(390, 30, 162, 305))
        self.bpExampleGraph_Label.setText("")
        self.bpExampleGraph_Label.setPixmap(QtGui.QPixmap(":/example/BP.png"))
        self.bpExampleGraph_Label.setScaledContents(True)
        self.bpExampleGraph_Label.setObjectName("bpExampleGraph_Label")
        self.frame_4 = QtWidgets.QFrame(self.bp_Tap)
        self.frame_4.setGeometry(QtCore.QRect(80, 80, 171, 41))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.bpHiddenTypeLinear_RadioButton = QtWidgets.QRadioButton(self.frame_4)
        self.bpHiddenTypeLinear_RadioButton.setGeometry(QtCore.QRect(10, 0, 70, 17))
        self.bpHiddenTypeLinear_RadioButton.setChecked(False)
        self.bpHiddenTypeLinear_RadioButton.setObjectName("bpHiddenTypeLinear_RadioButton")
        self.bpHiddenTypeSigmoid_RadioButton = QtWidgets.QRadioButton(self.frame_4)
        self.bpHiddenTypeSigmoid_RadioButton.setGeometry(QtCore.QRect(100, 0, 70, 17))
        self.bpHiddenTypeSigmoid_RadioButton.setObjectName("bpHiddenTypeSigmoid_RadioButton")
        self.bpHiddenTypeReLU_RadioButton = QtWidgets.QRadioButton(self.frame_4)
        self.bpHiddenTypeReLU_RadioButton.setGeometry(QtCore.QRect(100, 20, 70, 17))
        self.bpHiddenTypeReLU_RadioButton.setObjectName("bpHiddenTypeReLU_RadioButton")
        self.bpHiddenTypeTanh_RadioButton = QtWidgets.QRadioButton(self.frame_4)
        self.bpHiddenTypeTanh_RadioButton.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.bpHiddenTypeTanh_RadioButton.setChecked(True)
        self.bpHiddenTypeTanh_RadioButton.setObjectName("bpHiddenTypeTanh_RadioButton")
        self.order_TapWidget.addTab(self.bp_Tap, "")
        self.bptt_Tap = QtWidgets.QWidget()
        self.bptt_Tap.setObjectName("bptt_Tap")
        self.bpttHiddenLayer_Label = QtWidgets.QLabel(self.bptt_Tap)
        self.bpttHiddenLayer_Label.setGeometry(QtCore.QRect(20, 54, 47, 13))
        self.bpttHiddenLayer_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bpttHiddenLayer_Label.setObjectName("bpttHiddenLayer_Label")
        self.bpttTrainingApply_Button = QtWidgets.QPushButton(self.bptt_Tap)
        self.bpttTrainingApply_Button.setGeometry(QtCore.QRect(40, 240, 100, 30))
        self.bpttTrainingApply_Button.setObjectName("bpttTrainingApply_Button")
        self.bpttTestApply_Button = QtWidgets.QPushButton(self.bptt_Tap)
        self.bpttTestApply_Button.setGeometry(QtCore.QRect(150, 240, 100, 30))
        self.bpttTestApply_Button.setObjectName("bpttTestApply_Button")
        self.bpttOutputLayer_Label = QtWidgets.QLabel(self.bptt_Tap)
        self.bpttOutputLayer_Label.setGeometry(QtCore.QRect(20, 160, 47, 13))
        self.bpttOutputLayer_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bpttOutputLayer_Label.setObjectName("bpttOutputLayer_Label")
        self.bpttInputLayer_Label = QtWidgets.QLabel(self.bptt_Tap)
        self.bpttInputLayer_Label.setGeometry(QtCore.QRect(20, 24, 47, 13))
        self.bpttInputLayer_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bpttInputLayer_Label.setObjectName("bpttInputLayer_Label")
        self.bpttOutputLayer_ComboBox = QtWidgets.QComboBox(self.bptt_Tap)
        self.bpttOutputLayer_ComboBox.setGeometry(QtCore.QRect(80, 156, 171, 20))
        self.bpttOutputLayer_ComboBox.setObjectName("bpttOutputLayer_ComboBox")
        self.bpttExampleGraph_Label = QtWidgets.QLabel(self.bptt_Tap)
        self.bpttExampleGraph_Label.setGeometry(QtCore.QRect(300, 30, 317, 344))
        self.bpttExampleGraph_Label.setText("")
        self.bpttExampleGraph_Label.setPixmap(QtGui.QPixmap(":/example/BPTT.png"))
        self.bpttExampleGraph_Label.setScaledContents(True)
        self.bpttExampleGraph_Label.setObjectName("bpttExampleGraph_Label")
        self.bpttInputLayer_LineEdit = QtWidgets.QLineEdit(self.bptt_Tap)
        self.bpttInputLayer_LineEdit.setGeometry(QtCore.QRect(80, 20, 113, 20))
        self.bpttInputLayer_LineEdit.setObjectName("bpttInputLayer_LineEdit")
        self.bpttHiddenLayer_LineEdit = QtWidgets.QLineEdit(self.bptt_Tap)
        self.bpttHiddenLayer_LineEdit.setGeometry(QtCore.QRect(80, 50, 113, 20))
        self.bpttHiddenLayer_LineEdit.setText("")
        self.bpttHiddenLayer_LineEdit.setObjectName("bpttHiddenLayer_LineEdit")
        self.bpttTick_LineEdit = QtWidgets.QLineEdit(self.bptt_Tap)
        self.bpttTick_LineEdit.setGeometry(QtCore.QRect(80, 80, 61, 20))
        self.bpttTick_LineEdit.setObjectName("bpttTick_LineEdit")
        self.bpttTick_Label = QtWidgets.QLabel(self.bptt_Tap)
        self.bpttTick_Label.setGeometry(QtCore.QRect(20, 84, 47, 13))
        self.bpttTick_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bpttTick_Label.setObjectName("bpttTick_Label")
        self.bpttInitialReset_Label = QtWidgets.QLabel(self.bptt_Tap)
        self.bpttInitialReset_Label.setGeometry(QtCore.QRect(150, 80, 61, 20))
        self.bpttInitialReset_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bpttInitialReset_Label.setObjectName("bpttInitialReset_Label")
        self.bpttInitialReset_CheckBox = QtWidgets.QCheckBox(self.bptt_Tap)
        self.bpttInitialReset_CheckBox.setGeometry(QtCore.QRect(220, 84, 16, 17))
        self.bpttInitialReset_CheckBox.setText("")
        self.bpttInitialReset_CheckBox.setChecked(True)
        self.bpttInitialReset_CheckBox.setObjectName("bpttInitialReset_CheckBox")
        self.frame_5 = QtWidgets.QFrame(self.bptt_Tap)
        self.frame_5.setGeometry(QtCore.QRect(80, 110, 171, 41))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.bpttHiddenTypeLinear_RadioButton = QtWidgets.QRadioButton(self.frame_5)
        self.bpttHiddenTypeLinear_RadioButton.setGeometry(QtCore.QRect(10, 0, 70, 17))
        self.bpttHiddenTypeLinear_RadioButton.setChecked(False)
        self.bpttHiddenTypeLinear_RadioButton.setObjectName("bpttHiddenTypeLinear_RadioButton")
        self.bpttHiddenTypeSigmoid_RadioButton = QtWidgets.QRadioButton(self.frame_5)
        self.bpttHiddenTypeSigmoid_RadioButton.setGeometry(QtCore.QRect(100, 0, 70, 17))
        self.bpttHiddenTypeSigmoid_RadioButton.setObjectName("bpttHiddenTypeSigmoid_RadioButton")
        self.bpttHiddenTypeReLU_RadioButton = QtWidgets.QRadioButton(self.frame_5)
        self.bpttHiddenTypeReLU_RadioButton.setGeometry(QtCore.QRect(100, 20, 70, 17))
        self.bpttHiddenTypeReLU_RadioButton.setObjectName("bpttHiddenTypeReLU_RadioButton")
        self.bpttHiddenTypeTanh_RadioButton = QtWidgets.QRadioButton(self.frame_5)
        self.bpttHiddenTypeTanh_RadioButton.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.bpttHiddenTypeTanh_RadioButton.setChecked(True)
        self.bpttHiddenTypeTanh_RadioButton.setObjectName("bpttHiddenTypeTanh_RadioButton")
        self.frame_6 = QtWidgets.QFrame(self.bptt_Tap)
        self.frame_6.setGeometry(QtCore.QRect(80, 180, 171, 41))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.bpttOutputTypeLinear_RadioButton = QtWidgets.QRadioButton(self.frame_6)
        self.bpttOutputTypeLinear_RadioButton.setGeometry(QtCore.QRect(10, 0, 70, 17))
        self.bpttOutputTypeLinear_RadioButton.setChecked(False)
        self.bpttOutputTypeLinear_RadioButton.setObjectName("bpttOutputTypeLinear_RadioButton")
        self.bpttOutputTypeTanh_RadioButton = QtWidgets.QRadioButton(self.frame_6)
        self.bpttOutputTypeTanh_RadioButton.setGeometry(QtCore.QRect(100, 20, 70, 17))
        self.bpttOutputTypeTanh_RadioButton.setObjectName("bpttOutputTypeTanh_RadioButton")
        self.bpttOutputTypeSoftmax_RadioButton = QtWidgets.QRadioButton(self.frame_6)
        self.bpttOutputTypeSoftmax_RadioButton.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.bpttOutputTypeSoftmax_RadioButton.setObjectName("bpttOutputTypeSoftmax_RadioButton")
        self.bpttOutputTypeSigmoid_RadioButton = QtWidgets.QRadioButton(self.frame_6)
        self.bpttOutputTypeSigmoid_RadioButton.setGeometry(QtCore.QRect(100, 0, 70, 17))
        self.bpttOutputTypeSigmoid_RadioButton.setChecked(True)
        self.bpttOutputTypeSigmoid_RadioButton.setObjectName("bpttOutputTypeSigmoid_RadioButton")
        self.order_TapWidget.addTab(self.bptt_Tap, "")
        self.srn_Tap = QtWidgets.QWidget()
        self.srn_Tap.setObjectName("srn_Tap")
        self.srnTrainingApply_Button = QtWidgets.QPushButton(self.srn_Tap)
        self.srnTrainingApply_Button.setGeometry(QtCore.QRect(40, 280, 100, 30))
        self.srnTrainingApply_Button.setObjectName("srnTrainingApply_Button")
        self.srnContextLayer_Label = QtWidgets.QLabel(self.srn_Tap)
        self.srnContextLayer_Label.setGeometry(QtCore.QRect(20, 54, 47, 13))
        self.srnContextLayer_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.srnContextLayer_Label.setObjectName("srnContextLayer_Label")
        self.srnTestApply_Button = QtWidgets.QPushButton(self.srn_Tap)
        self.srnTestApply_Button.setGeometry(QtCore.QRect(150, 280, 100, 30))
        self.srnTestApply_Button.setObjectName("srnTestApply_Button")
        self.srnHiddenLayer_Label = QtWidgets.QLabel(self.srn_Tap)
        self.srnHiddenLayer_Label.setGeometry(QtCore.QRect(20, 84, 47, 13))
        self.srnHiddenLayer_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.srnHiddenLayer_Label.setObjectName("srnHiddenLayer_Label")
        self.srnInputLayer_Label = QtWidgets.QLabel(self.srn_Tap)
        self.srnInputLayer_Label.setGeometry(QtCore.QRect(20, 24, 47, 13))
        self.srnInputLayer_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.srnInputLayer_Label.setObjectName("srnInputLayer_Label")
        self.srnHiddenLayer_ComboBox = QtWidgets.QComboBox(self.srn_Tap)
        self.srnHiddenLayer_ComboBox.setGeometry(QtCore.QRect(80, 80, 170, 20))
        self.srnHiddenLayer_ComboBox.setObjectName("srnHiddenLayer_ComboBox")
        self.srnInputLayer_ComboBox = QtWidgets.QComboBox(self.srn_Tap)
        self.srnInputLayer_ComboBox.setGeometry(QtCore.QRect(80, 20, 170, 20))
        self.srnInputLayer_ComboBox.setObjectName("srnInputLayer_ComboBox")
        self.srnContextLayer_ComboBox = QtWidgets.QComboBox(self.srn_Tap)
        self.srnContextLayer_ComboBox.setGeometry(QtCore.QRect(80, 50, 170, 20))
        self.srnContextLayer_ComboBox.setObjectName("srnContextLayer_ComboBox")
        self.srnOutputLayer_ComboBox = QtWidgets.QComboBox(self.srn_Tap)
        self.srnOutputLayer_ComboBox.setGeometry(QtCore.QRect(80, 160, 170, 20))
        self.srnOutputLayer_ComboBox.setObjectName("srnOutputLayer_ComboBox")
        self.srnOutputLayer_Label = QtWidgets.QLabel(self.srn_Tap)
        self.srnOutputLayer_Label.setGeometry(QtCore.QRect(20, 164, 47, 13))
        self.srnOutputLayer_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.srnOutputLayer_Label.setObjectName("srnOutputLayer_Label")
        self.srnMaxCycle_LineEdit = QtWidgets.QLineEdit(self.srn_Tap)
        self.srnMaxCycle_LineEdit.setGeometry(QtCore.QRect(80, 240, 61, 20))
        self.srnMaxCycle_LineEdit.setObjectName("srnMaxCycle_LineEdit")
        self.srnExampleGraph_Label = QtWidgets.QLabel(self.srn_Tap)
        self.srnExampleGraph_Label.setGeometry(QtCore.QRect(270, 40, 371, 302))
        self.srnExampleGraph_Label.setText("")
        self.srnExampleGraph_Label.setPixmap(QtGui.QPixmap(":/example/SRN.png"))
        self.srnExampleGraph_Label.setScaledContents(True)
        self.srnExampleGraph_Label.setObjectName("srnExampleGraph_Label")
        self.srnMaxCycle_Label = QtWidgets.QLabel(self.srn_Tap)
        self.srnMaxCycle_Label.setGeometry(QtCore.QRect(20, 240, 50, 20))
        self.srnMaxCycle_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.srnMaxCycle_Label.setObjectName("srnMaxCycle_Label")
        self.frame_11 = QtWidgets.QFrame(self.srn_Tap)
        self.frame_11.setGeometry(QtCore.QRect(80, 190, 171, 41))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.srnOutputTypeLinear_RadioButton = QtWidgets.QRadioButton(self.frame_11)
        self.srnOutputTypeLinear_RadioButton.setGeometry(QtCore.QRect(10, 0, 70, 17))
        self.srnOutputTypeLinear_RadioButton.setChecked(False)
        self.srnOutputTypeLinear_RadioButton.setObjectName("srnOutputTypeLinear_RadioButton")
        self.srnOutputTypeTanh_RadioButton = QtWidgets.QRadioButton(self.frame_11)
        self.srnOutputTypeTanh_RadioButton.setGeometry(QtCore.QRect(100, 20, 70, 17))
        self.srnOutputTypeTanh_RadioButton.setObjectName("srnOutputTypeTanh_RadioButton")
        self.srnOutputTypeSoftmax_RadioButton = QtWidgets.QRadioButton(self.frame_11)
        self.srnOutputTypeSoftmax_RadioButton.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.srnOutputTypeSoftmax_RadioButton.setObjectName("srnOutputTypeSoftmax_RadioButton")
        self.srnOutputTypeSigmoid_RadioButton = QtWidgets.QRadioButton(self.frame_11)
        self.srnOutputTypeSigmoid_RadioButton.setGeometry(QtCore.QRect(100, 0, 70, 17))
        self.srnOutputTypeSigmoid_RadioButton.setChecked(True)
        self.srnOutputTypeSigmoid_RadioButton.setObjectName("srnOutputTypeSigmoid_RadioButton")
        self.frame_12 = QtWidgets.QFrame(self.srn_Tap)
        self.frame_12.setGeometry(QtCore.QRect(80, 110, 171, 41))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.srnHiddenTypeLinear_RadioButton = QtWidgets.QRadioButton(self.frame_12)
        self.srnHiddenTypeLinear_RadioButton.setGeometry(QtCore.QRect(10, 0, 70, 17))
        self.srnHiddenTypeLinear_RadioButton.setChecked(False)
        self.srnHiddenTypeLinear_RadioButton.setObjectName("srnHiddenTypeLinear_RadioButton")
        self.srnHiddenTypeSigmoid_RadioButton = QtWidgets.QRadioButton(self.frame_12)
        self.srnHiddenTypeSigmoid_RadioButton.setGeometry(QtCore.QRect(100, 0, 70, 17))
        self.srnHiddenTypeSigmoid_RadioButton.setObjectName("srnHiddenTypeSigmoid_RadioButton")
        self.srnHiddenTypeReLU_RadioButton = QtWidgets.QRadioButton(self.frame_12)
        self.srnHiddenTypeReLU_RadioButton.setGeometry(QtCore.QRect(100, 20, 70, 17))
        self.srnHiddenTypeReLU_RadioButton.setObjectName("srnHiddenTypeReLU_RadioButton")
        self.srnHiddenTypeTanh_RadioButton = QtWidgets.QRadioButton(self.frame_12)
        self.srnHiddenTypeTanh_RadioButton.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.srnHiddenTypeTanh_RadioButton.setChecked(True)
        self.srnHiddenTypeTanh_RadioButton.setObjectName("srnHiddenTypeTanh_RadioButton")
        self.order_TapWidget.addTab(self.srn_Tap, "")
        self.linear_Tap = QtWidgets.QWidget()
        self.linear_Tap.setObjectName("linear_Tap")
        self.linearForward_GroupBox = QtWidgets.QGroupBox(self.linear_Tap)
        self.linearForward_GroupBox.setGeometry(QtCore.QRect(10, 20, 651, 231))
        self.linearForward_GroupBox.setObjectName("linearForward_GroupBox")
        self.linearForwardLayer_ComboBox = QtWidgets.QComboBox(self.linearForward_GroupBox)
        self.linearForwardLayer_ComboBox.setGeometry(QtCore.QRect(270, 40, 101, 22))
        self.linearForwardLayer_ComboBox.setObjectName("linearForwardLayer_ComboBox")
        self.linearForwardDelete_Button = QtWidgets.QPushButton(self.linearForward_GroupBox)
        self.linearForwardDelete_Button.setGeometry(QtCore.QRect(10, 190, 151, 30))
        self.linearForwardDelete_Button.setObjectName("linearForwardDelete_Button")
        self.frame_7 = QtWidgets.QFrame(self.linearForward_GroupBox)
        self.frame_7.setGeometry(QtCore.QRect(270, 70, 141, 21))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.linearForwardFirstLayerTypeInput_RadioButton = QtWidgets.QRadioButton(self.frame_7)
        self.linearForwardFirstLayerTypeInput_RadioButton.setGeometry(QtCore.QRect(10, 2, 82, 17))
        self.linearForwardFirstLayerTypeInput_RadioButton.setChecked(True)
        self.linearForwardFirstLayerTypeInput_RadioButton.setObjectName("linearForwardFirstLayerTypeInput_RadioButton")
        self.linearForwardFirstLayerTypeHidden_RadioButton = QtWidgets.QRadioButton(self.frame_7)
        self.linearForwardFirstLayerTypeHidden_RadioButton.setGeometry(QtCore.QRect(70, 2, 82, 17))
        self.linearForwardFirstLayerTypeHidden_RadioButton.setObjectName("linearForwardFirstLayerTypeHidden_RadioButton")
        self.linearForwardApply_Button = QtWidgets.QPushButton(self.linearForward_GroupBox)
        self.linearForwardApply_Button.setGeometry(QtCore.QRect(540, 190, 100, 30))
        self.linearForwardApply_Button.setObjectName("linearForwardApply_Button")
        self.linearForwardLayer_Label = QtWidgets.QLabel(self.linearForward_GroupBox)
        self.linearForwardLayer_Label.setGeometry(QtCore.QRect(180, 44, 80, 13))
        self.linearForwardLayer_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linearForwardLayer_Label.setObjectName("linearForwardLayer_Label")
        self.linearForwardFirstLayerType_Label = QtWidgets.QLabel(self.linearForward_GroupBox)
        self.linearForwardFirstLayerType_Label.setGeometry(QtCore.QRect(170, 74, 95, 13))
        self.linearForwardFirstLayerType_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linearForwardFirstLayerType_Label.setObjectName("linearForwardFirstLayerType_Label")
        self.linearForwardLastLayerType_Label = QtWidgets.QLabel(self.linearForward_GroupBox)
        self.linearForwardLastLayerType_Label.setGeometry(QtCore.QRect(420, 74, 80, 13))
        self.linearForwardLastLayerType_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linearForwardLastLayerType_Label.setObjectName("linearForwardLastLayerType_Label")
        self.linearForwardAdd_Button = QtWidgets.QPushButton(self.linearForward_GroupBox)
        self.linearForwardAdd_Button.setGeometry(QtCore.QRect(380, 40, 75, 23))
        self.linearForwardAdd_Button.setObjectName("linearForwardAdd_Button")
        self.linearForwardLayer_ListWidget = QtWidgets.QListWidget(self.linearForward_GroupBox)
        self.linearForwardLayer_ListWidget.setGeometry(QtCore.QRect(10, 20, 151, 161))
        self.linearForwardLayer_ListWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.linearForwardLayer_ListWidget.setObjectName("linearForwardLayer_ListWidget")
        self.linearForwardActivationExtractforTest_CheckBox = QtWidgets.QCheckBox(self.linearForward_GroupBox)
        self.linearForwardActivationExtractforTest_CheckBox.setGeometry(QtCore.QRect(260, 160, 200, 17))
        self.linearForwardActivationExtractforTest_CheckBox.setObjectName("linearForwardActivationExtractforTest_CheckBox")
        self.frame_13 = QtWidgets.QFrame(self.linearForward_GroupBox)
        self.frame_13.setGeometry(QtCore.QRect(270, 100, 261, 21))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.linearForwardHiddenLayerTypeSigmoid_RadioButton = QtWidgets.QRadioButton(self.frame_13)
        self.linearForwardHiddenLayerTypeSigmoid_RadioButton.setGeometry(QtCore.QRect(70, 0, 60, 17))
        self.linearForwardHiddenLayerTypeSigmoid_RadioButton.setChecked(False)
        self.linearForwardHiddenLayerTypeSigmoid_RadioButton.setObjectName("linearForwardHiddenLayerTypeSigmoid_RadioButton")
        self.linearForwardHiddenLayerTypeTanh_RadioButton = QtWidgets.QRadioButton(self.frame_13)
        self.linearForwardHiddenLayerTypeTanh_RadioButton.setGeometry(QtCore.QRect(140, 0, 60, 17))
        self.linearForwardHiddenLayerTypeTanh_RadioButton.setChecked(True)
        self.linearForwardHiddenLayerTypeTanh_RadioButton.setObjectName("linearForwardHiddenLayerTypeTanh_RadioButton")
        self.linearForwardHiddenLayerTypeReLU_RadioButton = QtWidgets.QRadioButton(self.frame_13)
        self.linearForwardHiddenLayerTypeReLU_RadioButton.setGeometry(QtCore.QRect(210, 0, 60, 17))
        self.linearForwardHiddenLayerTypeReLU_RadioButton.setObjectName("linearForwardHiddenLayerTypeReLU_RadioButton")
        self.linearForwardHiddenLayerTypeLinear_RadioButton = QtWidgets.QRadioButton(self.frame_13)
        self.linearForwardHiddenLayerTypeLinear_RadioButton.setGeometry(QtCore.QRect(10, 0, 60, 17))
        self.linearForwardHiddenLayerTypeLinear_RadioButton.setChecked(False)
        self.linearForwardHiddenLayerTypeLinear_RadioButton.setObjectName("linearForwardHiddenLayerTypeLinear_RadioButton")
        self.linearForwardHiddenLayerType_Label = QtWidgets.QLabel(self.linearForward_GroupBox)
        self.linearForwardHiddenLayerType_Label.setGeometry(QtCore.QRect(170, 104, 95, 13))
        self.linearForwardHiddenLayerType_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linearForwardHiddenLayerType_Label.setObjectName("linearForwardHiddenLayerType_Label")
        self.frame_15 = QtWidgets.QFrame(self.linearForward_GroupBox)
        self.frame_15.setGeometry(QtCore.QRect(270, 130, 261, 21))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.linearForwardOutputLayerTypeSigmoid_RadioButton = QtWidgets.QRadioButton(self.frame_15)
        self.linearForwardOutputLayerTypeSigmoid_RadioButton.setGeometry(QtCore.QRect(70, 0, 60, 17))
        self.linearForwardOutputLayerTypeSigmoid_RadioButton.setChecked(True)
        self.linearForwardOutputLayerTypeSigmoid_RadioButton.setObjectName("linearForwardOutputLayerTypeSigmoid_RadioButton")
        self.linearForwardOutputLayerTypeTanh_RadioButton = QtWidgets.QRadioButton(self.frame_15)
        self.linearForwardOutputLayerTypeTanh_RadioButton.setGeometry(QtCore.QRect(210, 0, 60, 17))
        self.linearForwardOutputLayerTypeTanh_RadioButton.setChecked(False)
        self.linearForwardOutputLayerTypeTanh_RadioButton.setObjectName("linearForwardOutputLayerTypeTanh_RadioButton")
        self.linearForwardOutputLayerTypeLinear_RadioButton = QtWidgets.QRadioButton(self.frame_15)
        self.linearForwardOutputLayerTypeLinear_RadioButton.setGeometry(QtCore.QRect(10, 0, 60, 17))
        self.linearForwardOutputLayerTypeLinear_RadioButton.setChecked(False)
        self.linearForwardOutputLayerTypeLinear_RadioButton.setObjectName("linearForwardOutputLayerTypeLinear_RadioButton")
        self.linearForwardOutputLayerTypeSoftmax_RadioButton = QtWidgets.QRadioButton(self.frame_15)
        self.linearForwardOutputLayerTypeSoftmax_RadioButton.setGeometry(QtCore.QRect(140, 0, 60, 17))
        self.linearForwardOutputLayerTypeSoftmax_RadioButton.setObjectName("linearForwardOutputLayerTypeSoftmax_RadioButton")
        self.frame_14 = QtWidgets.QFrame(self.linearForward_GroupBox)
        self.frame_14.setGeometry(QtCore.QRect(500, 70, 141, 21))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.linearForwardLastLayerTypeOutput_RadioButton = QtWidgets.QRadioButton(self.frame_14)
        self.linearForwardLastLayerTypeOutput_RadioButton.setGeometry(QtCore.QRect(80, 2, 60, 17))
        self.linearForwardLastLayerTypeOutput_RadioButton.setChecked(True)
        self.linearForwardLastLayerTypeOutput_RadioButton.setObjectName("linearForwardLastLayerTypeOutput_RadioButton")
        self.linearForwardLastLayerTypeHidden_RadioButton = QtWidgets.QRadioButton(self.frame_14)
        self.linearForwardLastLayerTypeHidden_RadioButton.setGeometry(QtCore.QRect(10, 2, 60, 17))
        self.linearForwardLastLayerTypeHidden_RadioButton.setObjectName("linearForwardLastLayerTypeHidden_RadioButton")
        self.linearForwardOutputLayerType_Label = QtWidgets.QLabel(self.linearForward_GroupBox)
        self.linearForwardOutputLayerType_Label.setGeometry(QtCore.QRect(170, 130, 95, 13))
        self.linearForwardOutputLayerType_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linearForwardOutputLayerType_Label.setObjectName("linearForwardOutputLayerType_Label")
        self.linearBackword_GroupBox = QtWidgets.QGroupBox(self.linear_Tap)
        self.linearBackword_GroupBox.setGeometry(QtCore.QRect(10, 250, 651, 231))
        self.linearBackword_GroupBox.setObjectName("linearBackword_GroupBox")
        self.linearBackwardLayer_ComboBox = QtWidgets.QComboBox(self.linearBackword_GroupBox)
        self.linearBackwardLayer_ComboBox.setGeometry(QtCore.QRect(270, 40, 101, 22))
        self.linearBackwardLayer_ComboBox.setObjectName("linearBackwardLayer_ComboBox")
        self.linearBackwardDelete_Button = QtWidgets.QPushButton(self.linearBackword_GroupBox)
        self.linearBackwardDelete_Button.setGeometry(QtCore.QRect(10, 190, 151, 30))
        self.linearBackwardDelete_Button.setObjectName("linearBackwardDelete_Button")
        self.frame_9 = QtWidgets.QFrame(self.linearBackword_GroupBox)
        self.frame_9.setGeometry(QtCore.QRect(270, 130, 261, 21))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.linearBackwardHiddenLayerTypeSigmoid_RadioButton = QtWidgets.QRadioButton(self.frame_9)
        self.linearBackwardHiddenLayerTypeSigmoid_RadioButton.setGeometry(QtCore.QRect(70, 0, 71, 17))
        self.linearBackwardHiddenLayerTypeSigmoid_RadioButton.setObjectName("linearBackwardHiddenLayerTypeSigmoid_RadioButton")
        self.linearBackwardHiddenLayerTypeLinear_RadioButton = QtWidgets.QRadioButton(self.frame_9)
        self.linearBackwardHiddenLayerTypeLinear_RadioButton.setGeometry(QtCore.QRect(10, 0, 61, 17))
        self.linearBackwardHiddenLayerTypeLinear_RadioButton.setChecked(False)
        self.linearBackwardHiddenLayerTypeLinear_RadioButton.setObjectName("linearBackwardHiddenLayerTypeLinear_RadioButton")
        self.linearBackwardHiddenLayerTypeReLU_RadioButton = QtWidgets.QRadioButton(self.frame_9)
        self.linearBackwardHiddenLayerTypeReLU_RadioButton.setGeometry(QtCore.QRect(210, 0, 101, 17))
        self.linearBackwardHiddenLayerTypeReLU_RadioButton.setObjectName("linearBackwardHiddenLayerTypeReLU_RadioButton")
        self.linearBackwardHiddenLayerTypeTanh_RadioButton = QtWidgets.QRadioButton(self.frame_9)
        self.linearBackwardHiddenLayerTypeTanh_RadioButton.setGeometry(QtCore.QRect(140, 0, 61, 17))
        self.linearBackwardHiddenLayerTypeTanh_RadioButton.setChecked(True)
        self.linearBackwardHiddenLayerTypeTanh_RadioButton.setObjectName("linearBackwardHiddenLayerTypeTanh_RadioButton")
        self.frame_10 = QtWidgets.QFrame(self.linearBackword_GroupBox)
        self.frame_10.setGeometry(QtCore.QRect(270, 100, 261, 21))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.linearBackwardOutputLayerTypeSigmoid_RadioButton = QtWidgets.QRadioButton(self.frame_10)
        self.linearBackwardOutputLayerTypeSigmoid_RadioButton.setGeometry(QtCore.QRect(70, 0, 71, 17))
        self.linearBackwardOutputLayerTypeSigmoid_RadioButton.setChecked(True)
        self.linearBackwardOutputLayerTypeSigmoid_RadioButton.setObjectName("linearBackwardOutputLayerTypeSigmoid_RadioButton")
        self.linearBackwardOutputLayerTypeSoftmax_RadioButton = QtWidgets.QRadioButton(self.frame_10)
        self.linearBackwardOutputLayerTypeSoftmax_RadioButton.setGeometry(QtCore.QRect(140, 0, 71, 17))
        self.linearBackwardOutputLayerTypeSoftmax_RadioButton.setObjectName("linearBackwardOutputLayerTypeSoftmax_RadioButton")
        self.linearBackwardOutputLayerTypeLinear_RadioButton = QtWidgets.QRadioButton(self.frame_10)
        self.linearBackwardOutputLayerTypeLinear_RadioButton.setGeometry(QtCore.QRect(10, 0, 61, 17))
        self.linearBackwardOutputLayerTypeLinear_RadioButton.setChecked(False)
        self.linearBackwardOutputLayerTypeLinear_RadioButton.setObjectName("linearBackwardOutputLayerTypeLinear_RadioButton")
        self.linearBackwardOutputLayerTypeTanh_RadioButton = QtWidgets.QRadioButton(self.frame_10)
        self.linearBackwardOutputLayerTypeTanh_RadioButton.setGeometry(QtCore.QRect(210, 0, 101, 17))
        self.linearBackwardOutputLayerTypeTanh_RadioButton.setObjectName("linearBackwardOutputLayerTypeTanh_RadioButton")
        self.linearBackwardApply_Button = QtWidgets.QPushButton(self.linearBackword_GroupBox)
        self.linearBackwardApply_Button.setGeometry(QtCore.QRect(540, 190, 100, 30))
        self.linearBackwardApply_Button.setObjectName("linearBackwardApply_Button")
        self.linearBackwardLayer_Label = QtWidgets.QLabel(self.linearBackword_GroupBox)
        self.linearBackwardLayer_Label.setGeometry(QtCore.QRect(180, 44, 80, 13))
        self.linearBackwardLayer_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linearBackwardLayer_Label.setObjectName("linearBackwardLayer_Label")
        self.linearBackwardOutputLayerType_Label = QtWidgets.QLabel(self.linearBackword_GroupBox)
        self.linearBackwardOutputLayerType_Label.setGeometry(QtCore.QRect(170, 100, 95, 13))
        self.linearBackwardOutputLayerType_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linearBackwardOutputLayerType_Label.setObjectName("linearBackwardOutputLayerType_Label")
        self.linearBackwardHiddenLayerType_Label = QtWidgets.QLabel(self.linearBackword_GroupBox)
        self.linearBackwardHiddenLayerType_Label.setGeometry(QtCore.QRect(170, 130, 95, 13))
        self.linearBackwardHiddenLayerType_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linearBackwardHiddenLayerType_Label.setObjectName("linearBackwardHiddenLayerType_Label")
        self.linearBackwardAdd_Button = QtWidgets.QPushButton(self.linearBackword_GroupBox)
        self.linearBackwardAdd_Button.setGeometry(QtCore.QRect(380, 40, 75, 23))
        self.linearBackwardAdd_Button.setObjectName("linearBackwardAdd_Button")
        self.linearBackwardLayer_ListWidget = QtWidgets.QListWidget(self.linearBackword_GroupBox)
        self.linearBackwardLayer_ListWidget.setGeometry(QtCore.QRect(10, 20, 151, 161))
        self.linearBackwardLayer_ListWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.linearBackwardLayer_ListWidget.setObjectName("linearBackwardLayer_ListWidget")
        self.linearBackwardLastLayerType_Label = QtWidgets.QLabel(self.linearBackword_GroupBox)
        self.linearBackwardLastLayerType_Label.setGeometry(QtCore.QRect(420, 74, 80, 13))
        self.linearBackwardLastLayerType_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linearBackwardLastLayerType_Label.setObjectName("linearBackwardLastLayerType_Label")
        self.frame_8 = QtWidgets.QFrame(self.linearBackword_GroupBox)
        self.frame_8.setGeometry(QtCore.QRect(270, 70, 141, 21))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.linearBackwardFirstLayerTypeHidden_RadioButton = QtWidgets.QRadioButton(self.frame_8)
        self.linearBackwardFirstLayerTypeHidden_RadioButton.setGeometry(QtCore.QRect(10, 2, 82, 17))
        self.linearBackwardFirstLayerTypeHidden_RadioButton.setChecked(False)
        self.linearBackwardFirstLayerTypeHidden_RadioButton.setObjectName("linearBackwardFirstLayerTypeHidden_RadioButton")
        self.linearBackwardFirstLayerTypeOutput_RadioButton = QtWidgets.QRadioButton(self.frame_8)
        self.linearBackwardFirstLayerTypeOutput_RadioButton.setGeometry(QtCore.QRect(70, 2, 82, 17))
        self.linearBackwardFirstLayerTypeOutput_RadioButton.setChecked(True)
        self.linearBackwardFirstLayerTypeOutput_RadioButton.setObjectName("linearBackwardFirstLayerTypeOutput_RadioButton")
        self.frame_16 = QtWidgets.QFrame(self.linearBackword_GroupBox)
        self.frame_16.setGeometry(QtCore.QRect(500, 70, 141, 21))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.linearBackwardLastLayerTypeInput_RadioButton = QtWidgets.QRadioButton(self.frame_16)
        self.linearBackwardLastLayerTypeInput_RadioButton.setGeometry(QtCore.QRect(80, 2, 60, 17))
        self.linearBackwardLastLayerTypeInput_RadioButton.setChecked(True)
        self.linearBackwardLastLayerTypeInput_RadioButton.setObjectName("linearBackwardLastLayerTypeInput_RadioButton")
        self.linearBackwardLastLayerTypeHidden_RadioButton = QtWidgets.QRadioButton(self.frame_16)
        self.linearBackwardLastLayerTypeHidden_RadioButton.setGeometry(QtCore.QRect(10, 2, 60, 17))
        self.linearBackwardLastLayerTypeHidden_RadioButton.setObjectName("linearBackwardLastLayerTypeHidden_RadioButton")
        self.linearBackwardFirstLayerType_Label = QtWidgets.QLabel(self.linearBackword_GroupBox)
        self.linearBackwardFirstLayerType_Label.setGeometry(QtCore.QRect(170, 74, 95, 13))
        self.linearBackwardFirstLayerType_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linearBackwardFirstLayerType_Label.setObjectName("linearBackwardFirstLayerType_Label")
        self.linearEndInitialize_Button = QtWidgets.QPushButton(self.linear_Tap)
        self.linearEndInitialize_Button.setGeometry(QtCore.QRect(550, 490, 100, 50))
        self.linearEndInitialize_Button.setObjectName("linearEndInitialize_Button")
        self.order_TapWidget.addTab(self.linear_Tap, "")
        self.custom_Tap = QtWidgets.QWidget()
        self.custom_Tap.setObjectName("custom_Tap")
        self.customLayerInitialize_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customLayerInitialize_Button.setGeometry(QtCore.QRect(120, 320, 100, 50))
        self.customLayerInitialize_Button.setObjectName("customLayerInitialize_Button")
        self.customEndInitialize_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customEndInitialize_Button.setGeometry(QtCore.QRect(120, 200, 101, 50))
        self.customEndInitialize_Button.setObjectName("customEndInitialize_Button")
        self.customInputLayerActivationInsert_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customInputLayerActivationInsert_Button.setGeometry(QtCore.QRect(10, 80, 100, 50))
        self.customInputLayerActivationInsert_Button.setObjectName("customInputLayerActivationInsert_Button")
        self.customLayerActivationCalculationSigmoid_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customLayerActivationCalculationSigmoid_Button.setGeometry(QtCore.QRect(340, 140, 100, 50))
        self.customLayerActivationCalculationSigmoid_Button.setObjectName("customLayerActivationCalculationSigmoid_Button")
        self.customLayerActivationCalculationSoftmax_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customLayerActivationCalculationSoftmax_Button.setGeometry(QtCore.QRect(340, 200, 100, 50))
        self.customLayerActivationCalculationSoftmax_Button.setObjectName("customLayerActivationCalculationSoftmax_Button")
        self.customLayerActivationSend_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customLayerActivationSend_Button.setGeometry(QtCore.QRect(120, 80, 100, 50))
        self.customLayerActivationSend_Button.setObjectName("customLayerActivationSend_Button")
        self.customOutputLayerErrorCalculationSigmoid_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customOutputLayerErrorCalculationSigmoid_Button.setGeometry(QtCore.QRect(450, 140, 100, 50))
        self.customOutputLayerErrorCalculationSigmoid_Button.setObjectName("customOutputLayerErrorCalculationSigmoid_Button")
        self.customOutputLayerErrorCalculationSoftmax_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customOutputLayerErrorCalculationSoftmax_Button.setGeometry(QtCore.QRect(450, 200, 100, 50))
        self.customOutputLayerErrorCalculationSoftmax_Button.setObjectName("customOutputLayerErrorCalculationSoftmax_Button")
        self.customHiddenLayerErrorCalculationSigmoid_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customHiddenLayerErrorCalculationSigmoid_Button.setGeometry(QtCore.QRect(560, 140, 100, 50))
        self.customHiddenLayerErrorCalculationSigmoid_Button.setObjectName("customHiddenLayerErrorCalculationSigmoid_Button")
        self.customHiddenLayerErrorCalculationReLU_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customHiddenLayerErrorCalculationReLU_Button.setGeometry(QtCore.QRect(560, 320, 100, 50))
        self.customHiddenLayerErrorCalculationReLU_Button.setObjectName("customHiddenLayerErrorCalculationReLU_Button")
        self.customBiasRenewal_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customBiasRenewal_Button.setGeometry(QtCore.QRect(120, 140, 100, 50))
        self.customBiasRenewal_Button.setObjectName("customBiasRenewal_Button")
        self.customWeightRenewal_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customWeightRenewal_Button.setGeometry(QtCore.QRect(230, 140, 100, 50))
        self.customWeightRenewal_Button.setObjectName("customWeightRenewal_Button")
        self.customLayerDuplicate_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customLayerDuplicate_Button.setGeometry(QtCore.QRect(10, 320, 100, 50))
        self.customLayerDuplicate_Button.setObjectName("customLayerDuplicate_Button")
        self.customConnectionDuplicate_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customConnectionDuplicate_Button.setGeometry(QtCore.QRect(120, 380, 100, 50))
        self.customConnectionDuplicate_Button.setObjectName("customConnectionDuplicate_Button")
        self.customTransposedConnectionDuplicate_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customTransposedConnectionDuplicate_Button.setGeometry(QtCore.QRect(10, 380, 100, 50))
        self.customTransposedConnectionDuplicate_Button.setObjectName("customTransposedConnectionDuplicate_Button")
        self.customLayer1_Label = QtWidgets.QLabel(self.custom_Tap)
        self.customLayer1_Label.setGeometry(QtCore.QRect(9, 14, 61, 20))
        self.customLayer1_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.customLayer1_Label.setObjectName("customLayer1_Label")
        self.customLayer2_Label = QtWidgets.QLabel(self.custom_Tap)
        self.customLayer2_Label.setGeometry(QtCore.QRect(10, 44, 61, 13))
        self.customLayer2_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.customLayer2_Label.setObjectName("customLayer2_Label")
        self.customConnection1_Label = QtWidgets.QLabel(self.custom_Tap)
        self.customConnection1_Label.setGeometry(QtCore.QRect(330, 14, 80, 13))
        self.customConnection1_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.customConnection1_Label.setObjectName("customConnection1_Label")
        self.customConnection2_Label = QtWidgets.QLabel(self.custom_Tap)
        self.customConnection2_Label.setGeometry(QtCore.QRect(330, 44, 80, 13))
        self.customConnection2_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.customConnection2_Label.setObjectName("customConnection2_Label")
        self.customLayer1_ComboBox = QtWidgets.QComboBox(self.custom_Tap)
        self.customLayer1_ComboBox.setGeometry(QtCore.QRect(80, 10, 210, 22))
        self.customLayer1_ComboBox.setObjectName("customLayer1_ComboBox")
        self.customLayer2_ComboBox = QtWidgets.QComboBox(self.custom_Tap)
        self.customLayer2_ComboBox.setEnabled(False)
        self.customLayer2_ComboBox.setGeometry(QtCore.QRect(80, 40, 210, 22))
        self.customLayer2_ComboBox.setObjectName("customLayer2_ComboBox")
        self.customConnection1_ComboBox = QtWidgets.QComboBox(self.custom_Tap)
        self.customConnection1_ComboBox.setGeometry(QtCore.QRect(420, 10, 210, 22))
        self.customConnection1_ComboBox.setObjectName("customConnection1_ComboBox")
        self.customConnection2_ComboBox = QtWidgets.QComboBox(self.custom_Tap)
        self.customConnection2_ComboBox.setEnabled(False)
        self.customConnection2_ComboBox.setGeometry(QtCore.QRect(420, 40, 210, 22))
        self.customConnection2_ComboBox.setObjectName("customConnection2_ComboBox")
        self.customWeightEqualization_GroupBox = QtWidgets.QGroupBox(self.custom_Tap)
        self.customWeightEqualization_GroupBox.setGeometry(QtCore.QRect(450, 370, 211, 181))
        self.customWeightEqualization_GroupBox.setObjectName("customWeightEqualization_GroupBox")
        self.customWeightEqualization_Button = QtWidgets.QPushButton(self.customWeightEqualization_GroupBox)
        self.customWeightEqualization_Button.setGeometry(QtCore.QRect(10, 130, 191, 41))
        self.customWeightEqualization_Button.setObjectName("customWeightEqualization_Button")
        self.customWeightEqualizationConnection_ComboBox = QtWidgets.QComboBox(self.customWeightEqualization_GroupBox)
        self.customWeightEqualizationConnection_ComboBox.setGeometry(QtCore.QRect(10, 100, 131, 22))
        self.customWeightEqualizationConnection_ComboBox.setObjectName("customWeightEqualizationConnection_ComboBox")
        self.customWeightEqualizationConnectionDelete_Button = QtWidgets.QPushButton(self.customWeightEqualization_GroupBox)
        self.customWeightEqualizationConnectionDelete_Button.setGeometry(QtCore.QRect(10, 75, 191, 22))
        self.customWeightEqualizationConnectionDelete_Button.setObjectName("customWeightEqualizationConnectionDelete_Button")
        self.customWeightEqualizationConnectionAdd_Button = QtWidgets.QPushButton(self.customWeightEqualization_GroupBox)
        self.customWeightEqualizationConnectionAdd_Button.setGeometry(QtCore.QRect(150, 100, 51, 22))
        self.customWeightEqualizationConnectionAdd_Button.setObjectName("customWeightEqualizationConnectionAdd_Button")
        self.customWeightEqualization_ListWidget = QtWidgets.QListWidget(self.customWeightEqualization_GroupBox)
        self.customWeightEqualization_ListWidget.setGeometry(QtCore.QRect(10, 20, 191, 51))
        self.customWeightEqualization_ListWidget.setObjectName("customWeightEqualization_ListWidget")
        self.customLayerActivationCalculationReLU_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customLayerActivationCalculationReLU_Button.setGeometry(QtCore.QRect(340, 320, 100, 50))
        self.customLayerActivationCalculationReLU_Button.setObjectName("customLayerActivationCalculationReLU_Button")
        self.customBiasEqualization_GroupBox = QtWidgets.QGroupBox(self.custom_Tap)
        self.customBiasEqualization_GroupBox.setGeometry(QtCore.QRect(230, 370, 211, 181))
        self.customBiasEqualization_GroupBox.setObjectName("customBiasEqualization_GroupBox")
        self.customBiasEqualization_Button = QtWidgets.QPushButton(self.customBiasEqualization_GroupBox)
        self.customBiasEqualization_Button.setGeometry(QtCore.QRect(10, 130, 191, 41))
        self.customBiasEqualization_Button.setObjectName("customBiasEqualization_Button")
        self.customBiasEqualizationLayer_ComboBox = QtWidgets.QComboBox(self.customBiasEqualization_GroupBox)
        self.customBiasEqualizationLayer_ComboBox.setGeometry(QtCore.QRect(10, 100, 131, 22))
        self.customBiasEqualizationLayer_ComboBox.setObjectName("customBiasEqualizationLayer_ComboBox")
        self.customBiasEqualizationDelete_Button = QtWidgets.QPushButton(self.customBiasEqualization_GroupBox)
        self.customBiasEqualizationDelete_Button.setGeometry(QtCore.QRect(10, 75, 191, 22))
        self.customBiasEqualizationDelete_Button.setObjectName("customBiasEqualizationDelete_Button")
        self.customBiasEqualizationAdd_Button = QtWidgets.QPushButton(self.customBiasEqualization_GroupBox)
        self.customBiasEqualizationAdd_Button.setGeometry(QtCore.QRect(150, 100, 51, 22))
        self.customBiasEqualizationAdd_Button.setObjectName("customBiasEqualizationAdd_Button")
        self.customBiasEqualization_ListWidget = QtWidgets.QListWidget(self.customBiasEqualization_GroupBox)
        self.customBiasEqualization_ListWidget.setGeometry(QtCore.QRect(10, 20, 191, 51))
        self.customBiasEqualization_ListWidget.setObjectName("customBiasEqualization_ListWidget")
        self.customErrorSend_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customErrorSend_Button.setGeometry(QtCore.QRect(10, 140, 100, 50))
        self.customErrorSend_Button.setObjectName("customErrorSend_Button")
        self.customActivationExtract_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customActivationExtract_Button.setGeometry(QtCore.QRect(230, 80, 100, 50))
        self.customActivationExtract_Button.setObjectName("customActivationExtract_Button")
        self.customCycleMarker_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customCycleMarker_Button.setGeometry(QtCore.QRect(230, 320, 100, 50))
        self.customCycleMarker_Button.setObjectName("customCycleMarker_Button")
        self.randomizeActivationInsert_GroupBox = QtWidgets.QGroupBox(self.custom_Tap)
        self.randomizeActivationInsert_GroupBox.setGeometry(QtCore.QRect(10, 450, 211, 101))
        self.randomizeActivationInsert_GroupBox.setObjectName("randomizeActivationInsert_GroupBox")
        self.customUniformRandomActivationInsert_Button = QtWidgets.QPushButton(self.randomizeActivationInsert_GroupBox)
        self.customUniformRandomActivationInsert_Button.setGeometry(QtCore.QRect(10, 50, 91, 41))
        self.customUniformRandomActivationInsert_Button.setObjectName("customUniformRandomActivationInsert_Button")
        self.customNormalRandomActivationInsert_Button = QtWidgets.QPushButton(self.randomizeActivationInsert_GroupBox)
        self.customNormalRandomActivationInsert_Button.setGeometry(QtCore.QRect(110, 50, 91, 41))
        self.customNormalRandomActivationInsert_Button.setObjectName("customNormalRandomActivationInsert_Button")
        self.customRandomActivationCriteria_Label = QtWidgets.QLabel(self.randomizeActivationInsert_GroupBox)
        self.customRandomActivationCriteria_Label.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.customRandomActivationCriteria_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.customRandomActivationCriteria_Label.setObjectName("customRandomActivationCriteria_Label")
        self.customRandomActivationCriteria_LineEdit = QtWidgets.QLineEdit(self.randomizeActivationInsert_GroupBox)
        self.customRandomActivationCriteria_LineEdit.setGeometry(QtCore.QRect(102, 20, 101, 20))
        self.customRandomActivationCriteria_LineEdit.setObjectName("customRandomActivationCriteria_LineEdit")
        self.customOutputLayerErrorCalculationLinear_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customOutputLayerErrorCalculationLinear_Button.setGeometry(QtCore.QRect(450, 80, 100, 50))
        self.customOutputLayerErrorCalculationLinear_Button.setObjectName("customOutputLayerErrorCalculationLinear_Button")
        self.customLayerActivationCalculationLinear_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customLayerActivationCalculationLinear_Button.setGeometry(QtCore.QRect(340, 80, 100, 50))
        self.customLayerActivationCalculationLinear_Button.setObjectName("customLayerActivationCalculationLinear_Button")
        self.customHiddenLayerErrorCalculationLinear_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customHiddenLayerErrorCalculationLinear_Button.setGeometry(QtCore.QRect(560, 80, 100, 50))
        self.customHiddenLayerErrorCalculationLinear_Button.setObjectName("customHiddenLayerErrorCalculationLinear_Button")
        self.customHiddenLayerErrorCalculationTanh_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customHiddenLayerErrorCalculationTanh_Button.setGeometry(QtCore.QRect(560, 260, 100, 50))
        self.customHiddenLayerErrorCalculationTanh_Button.setObjectName("customHiddenLayerErrorCalculationTanh_Button")
        self.customLayerActivationCalculationTanh_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customLayerActivationCalculationTanh_Button.setGeometry(QtCore.QRect(340, 260, 100, 50))
        self.customLayerActivationCalculationTanh_Button.setObjectName("customLayerActivationCalculationTanh_Button")
        self.customOutputLayerErrorCalculationTanh_Button = QtWidgets.QPushButton(self.custom_Tap)
        self.customOutputLayerErrorCalculationTanh_Button.setGeometry(QtCore.QRect(450, 260, 100, 50))
        self.customOutputLayerErrorCalculationTanh_Button.setObjectName("customOutputLayerErrorCalculationTanh_Button")
        self.order_TapWidget.addTab(self.custom_Tap, "")
        self.processSave_Button = QtWidgets.QPushButton(Dialog)
        self.processSave_Button.setGeometry(QtCore.QRect(270, 780, 120, 30))
        self.processSave_Button.setObjectName("processSave_Button")
        self.processLoad_Button = QtWidgets.QPushButton(Dialog)
        self.processLoad_Button.setGeometry(QtCore.QRect(430, 780, 120, 30))
        self.processLoad_Button.setObjectName("processLoad_Button")
        self.exit_Button = QtWidgets.QPushButton(Dialog)
        self.exit_Button.setGeometry(QtCore.QRect(590, 780, 120, 30))
        self.exit_Button.setObjectName("exit_Button")
        self.order_ListWidget = QtWidgets.QListWidget(Dialog)
        self.order_ListWidget.setGeometry(QtCore.QRect(10, 187, 256, 541))
        self.order_ListWidget.setObjectName("order_ListWidget")

        self.retranslateUi(Dialog)
        self.order_TapWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Process Setup"))
        self.process_GroupBox.setTitle(_translate("Dialog", "Process"))
        self.processDelete_Button.setText(_translate("Dialog", "Delete"))
        self.processName_Label.setText(_translate("Dialog", "Process Name"))
        self.processMaking_Button.setText(_translate("Dialog", "Making"))
        self.processModify_Button.setText(_translate("Dialog", "Modify"))
        self.processEnd_Button.setText(_translate("Dialog", "End"))
        self.layerControl_GroupBox.setTitle(_translate("Dialog", "Layer Control"))
        self.layerOn_Button.setText(_translate("Dialog", "On"))
        self.layerDamage_Button.setText(_translate("Dialog", "Damage"))
        self.layerOff_Button.setText(_translate("Dialog", "Off"))
        self.layerDamageSD_LineEdit.setText(_translate("Dialog", "0.1"))
        self.layerDamageSD_Label.setText(_translate("Dialog", "SD"))
        self.connectionControl_GroupBox.setTitle(_translate("Dialog", "Connection Control"))
        self.connectionOn_Button.setText(_translate("Dialog", "On"))
        self.connectionDamageSD_LineEdit.setText(_translate("Dialog", "0.1"))
        self.connectionOff_Button.setText(_translate("Dialog", "Off"))
        self.connectionDamageSD_Label.setText(_translate("Dialog", "SD"))
        self.connectionDamage_Button.setText(_translate("Dialog", "Damage"))
        self.orderDown_Button.setText(_translate("Dialog", "▼"))
        self.orderDelete_Button.setText(_translate("Dialog", "Delete"))
        self.orderUp_Button.setText(_translate("Dialog", "▲"))
        self.bpInputLayer_Label.setText(_translate("Dialog", "Input"))
        self.bpHiddenLayer_Label.setText(_translate("Dialog", "Hidden"))
        self.bpOutputLayer_Label.setText(_translate("Dialog", "Output"))
        self.bpOutputTypeLinear_RadioButton.setText(_translate("Dialog", "Linear"))
        self.bpOutputTypeTanh_RadioButton.setText(_translate("Dialog", "Tanh"))
        self.bpOutputTypeSoftmax_RadioButton.setText(_translate("Dialog", "Softmax"))
        self.bpOutputTypeSigmoid_RadioButton.setText(_translate("Dialog", "Sigmoid"))
        self.bpTrainingApply_Button.setText(_translate("Dialog", "Training Apply"))
        self.bpTestApply_Button.setText(_translate("Dialog", "Test Apply"))
        self.bpHiddenTypeLinear_RadioButton.setText(_translate("Dialog", "Linear"))
        self.bpHiddenTypeSigmoid_RadioButton.setText(_translate("Dialog", "Sigmoid"))
        self.bpHiddenTypeReLU_RadioButton.setText(_translate("Dialog", "ReLU"))
        self.bpHiddenTypeTanh_RadioButton.setText(_translate("Dialog", "Tanh"))
        self.order_TapWidget.setTabText(self.order_TapWidget.indexOf(self.bp_Tap), _translate("Dialog", "Back-Propagation Order"))
        self.bpttHiddenLayer_Label.setText(_translate("Dialog", "Hidden"))
        self.bpttTrainingApply_Button.setText(_translate("Dialog", "Training Apply"))
        self.bpttTestApply_Button.setText(_translate("Dialog", "Test Apply"))
        self.bpttOutputLayer_Label.setText(_translate("Dialog", "Output"))
        self.bpttInputLayer_Label.setText(_translate("Dialog", "Input"))
        self.bpttTick_Label.setText(_translate("Dialog", "Tick"))
        self.bpttInitialReset_Label.setText(_translate("Dialog", "Initial Reset"))
        self.bpttHiddenTypeLinear_RadioButton.setText(_translate("Dialog", "Linear"))
        self.bpttHiddenTypeSigmoid_RadioButton.setText(_translate("Dialog", "Sigmoid"))
        self.bpttHiddenTypeReLU_RadioButton.setText(_translate("Dialog", "ReLU"))
        self.bpttHiddenTypeTanh_RadioButton.setText(_translate("Dialog", "Tanh"))
        self.bpttOutputTypeLinear_RadioButton.setText(_translate("Dialog", "Linear"))
        self.bpttOutputTypeTanh_RadioButton.setText(_translate("Dialog", "Tanh"))
        self.bpttOutputTypeSoftmax_RadioButton.setText(_translate("Dialog", "Softmax"))
        self.bpttOutputTypeSigmoid_RadioButton.setText(_translate("Dialog", "Sigmoid"))
        self.order_TapWidget.setTabText(self.order_TapWidget.indexOf(self.bptt_Tap), _translate("Dialog", "BP Through Time Order"))
        self.srnTrainingApply_Button.setText(_translate("Dialog", "Training Apply"))
        self.srnContextLayer_Label.setText(_translate("Dialog", "Context"))
        self.srnTestApply_Button.setText(_translate("Dialog", "Test Apply"))
        self.srnHiddenLayer_Label.setText(_translate("Dialog", "Hidden"))
        self.srnInputLayer_Label.setText(_translate("Dialog", "Input"))
        self.srnOutputLayer_Label.setText(_translate("Dialog", "Output"))
        self.srnMaxCycle_Label.setText(_translate("Dialog", "Max Cycle"))
        self.srnOutputTypeLinear_RadioButton.setText(_translate("Dialog", "Linear"))
        self.srnOutputTypeTanh_RadioButton.setText(_translate("Dialog", "Tanh"))
        self.srnOutputTypeSoftmax_RadioButton.setText(_translate("Dialog", "Softmax"))
        self.srnOutputTypeSigmoid_RadioButton.setText(_translate("Dialog", "Sigmoid"))
        self.srnHiddenTypeLinear_RadioButton.setText(_translate("Dialog", "Linear"))
        self.srnHiddenTypeSigmoid_RadioButton.setText(_translate("Dialog", "Sigmoid"))
        self.srnHiddenTypeReLU_RadioButton.setText(_translate("Dialog", "ReLU"))
        self.srnHiddenTypeTanh_RadioButton.setText(_translate("Dialog", "Tanh"))
        self.order_TapWidget.setTabText(self.order_TapWidget.indexOf(self.srn_Tap), _translate("Dialog", "SRN Order"))
        self.linearForward_GroupBox.setTitle(_translate("Dialog", "Forward Order"))
        self.linearForwardDelete_Button.setText(_translate("Dialog", "Last Delete"))
        self.linearForwardFirstLayerTypeInput_RadioButton.setText(_translate("Dialog", "Input"))
        self.linearForwardFirstLayerTypeHidden_RadioButton.setText(_translate("Dialog", "Hidden"))
        self.linearForwardApply_Button.setText(_translate("Dialog", "Apply"))
        self.linearForwardLayer_Label.setText(_translate("Dialog", "Layer"))
        self.linearForwardFirstLayerType_Label.setText(_translate("Dialog", "First Layer Type"))
        self.linearForwardLastLayerType_Label.setText(_translate("Dialog", "Last Layer Type"))
        self.linearForwardAdd_Button.setText(_translate("Dialog", "Add"))
        self.linearForwardActivationExtractforTest_CheckBox.setText(_translate("Dialog", "Include Activation Extract for Test"))
        self.linearForwardHiddenLayerTypeSigmoid_RadioButton.setText(_translate("Dialog", "Sigmoid"))
        self.linearForwardHiddenLayerTypeTanh_RadioButton.setText(_translate("Dialog", "Tanh"))
        self.linearForwardHiddenLayerTypeReLU_RadioButton.setText(_translate("Dialog", "ReLU"))
        self.linearForwardHiddenLayerTypeLinear_RadioButton.setText(_translate("Dialog", "Linear"))
        self.linearForwardHiddenLayerType_Label.setText(_translate("Dialog", "Hidden Layer Type"))
        self.linearForwardOutputLayerTypeSigmoid_RadioButton.setText(_translate("Dialog", "Sigmoid"))
        self.linearForwardOutputLayerTypeTanh_RadioButton.setText(_translate("Dialog", "Tanh"))
        self.linearForwardOutputLayerTypeLinear_RadioButton.setText(_translate("Dialog", "Linear"))
        self.linearForwardOutputLayerTypeSoftmax_RadioButton.setText(_translate("Dialog", "Softmax"))
        self.linearForwardLastLayerTypeOutput_RadioButton.setText(_translate("Dialog", "Output"))
        self.linearForwardLastLayerTypeHidden_RadioButton.setText(_translate("Dialog", "Hidden"))
        self.linearForwardOutputLayerType_Label.setText(_translate("Dialog", "Output Layer Type"))
        self.linearBackword_GroupBox.setTitle(_translate("Dialog", "Backward Order"))
        self.linearBackwardDelete_Button.setText(_translate("Dialog", "Last Delete"))
        self.linearBackwardHiddenLayerTypeSigmoid_RadioButton.setText(_translate("Dialog", "Sigmoid"))
        self.linearBackwardHiddenLayerTypeLinear_RadioButton.setText(_translate("Dialog", "Linear"))
        self.linearBackwardHiddenLayerTypeReLU_RadioButton.setText(_translate("Dialog", "ReLU"))
        self.linearBackwardHiddenLayerTypeTanh_RadioButton.setText(_translate("Dialog", "Tanh"))
        self.linearBackwardOutputLayerTypeSigmoid_RadioButton.setText(_translate("Dialog", "Sigmoid"))
        self.linearBackwardOutputLayerTypeSoftmax_RadioButton.setText(_translate("Dialog", "Softmax"))
        self.linearBackwardOutputLayerTypeLinear_RadioButton.setText(_translate("Dialog", "Linear"))
        self.linearBackwardOutputLayerTypeTanh_RadioButton.setText(_translate("Dialog", "Tanh"))
        self.linearBackwardApply_Button.setText(_translate("Dialog", "Apply"))
        self.linearBackwardLayer_Label.setText(_translate("Dialog", "Layer"))
        self.linearBackwardOutputLayerType_Label.setText(_translate("Dialog", "Output Layer Type"))
        self.linearBackwardHiddenLayerType_Label.setText(_translate("Dialog", "Hidden Layer Type"))
        self.linearBackwardAdd_Button.setText(_translate("Dialog", "Add"))
        self.linearBackwardLastLayerType_Label.setText(_translate("Dialog", "Last Layer Type"))
        self.linearBackwardFirstLayerTypeHidden_RadioButton.setText(_translate("Dialog", "Hidden"))
        self.linearBackwardFirstLayerTypeOutput_RadioButton.setText(_translate("Dialog", "Output"))
        self.linearBackwardLastLayerTypeInput_RadioButton.setText(_translate("Dialog", "Input"))
        self.linearBackwardLastLayerTypeHidden_RadioButton.setText(_translate("Dialog", "Hidden"))
        self.linearBackwardFirstLayerType_Label.setText(_translate("Dialog", "First Layer Type"))
        self.linearEndInitialize_Button.setText(_translate("Dialog", "End && Initialize"))
        self.order_TapWidget.setTabText(self.order_TapWidget.indexOf(self.linear_Tap), _translate("Dialog", "Linear Order"))
        self.customLayerInitialize_Button.setText(_translate("Dialog", "Layer Initialize"))
        self.customEndInitialize_Button.setText(_translate("Dialog", "End && Initialize"))
        self.customInputLayerActivationInsert_Button.setText(_translate("Dialog", "Activation\n"
"Insert"))
        self.customLayerActivationCalculationSigmoid_Button.setText(_translate("Dialog", "Activation\n"
"Calculation\n"
"(Sigmoid)"))
        self.customLayerActivationCalculationSoftmax_Button.setText(_translate("Dialog", "Activation\n"
"Calculation\n"
"(Softmax)"))
        self.customLayerActivationSend_Button.setText(_translate("Dialog", "Activation Send"))
        self.customOutputLayerErrorCalculationSigmoid_Button.setText(_translate("Dialog", "Output Layer\n"
"Error Calc.\n"
"(Sigmoid)"))
        self.customOutputLayerErrorCalculationSoftmax_Button.setText(_translate("Dialog", "Output Layer\n"
"Error Calc.\n"
"(Softmax)"))
        self.customHiddenLayerErrorCalculationSigmoid_Button.setText(_translate("Dialog", "Hidden Layer\n"
"Error Calc.\n"
"(Sigmoid)"))
        self.customHiddenLayerErrorCalculationReLU_Button.setText(_translate("Dialog", "Hidden Layer\n"
"Error Calc.\n"
"(ReLU)"))
        self.customBiasRenewal_Button.setText(_translate("Dialog", "Bias Renewal"))
        self.customWeightRenewal_Button.setText(_translate("Dialog", "Weight Renewal"))
        self.customLayerDuplicate_Button.setText(_translate("Dialog", "Layer\n"
"Duplication"))
        self.customConnectionDuplicate_Button.setText(_translate("Dialog", "Connection\n"
"Duplication"))
        self.customTransposedConnectionDuplicate_Button.setText(_translate("Dialog", "Transposed\n"
"Connection\n"
"Duplication"))
        self.customLayer1_Label.setText(_translate("Dialog", "Layer 1"))
        self.customLayer2_Label.setText(_translate("Dialog", "Layer 2"))
        self.customConnection1_Label.setText(_translate("Dialog", "Connection 1"))
        self.customConnection2_Label.setText(_translate("Dialog", "Connection 2"))
        self.customWeightEqualization_GroupBox.setTitle(_translate("Dialog", "Weight Equalization"))
        self.customWeightEqualization_Button.setText(_translate("Dialog", "Weight Equalization"))
        self.customWeightEqualizationConnectionDelete_Button.setText(_translate("Dialog", "Delete"))
        self.customWeightEqualizationConnectionAdd_Button.setText(_translate("Dialog", "Add"))
        self.customLayerActivationCalculationReLU_Button.setText(_translate("Dialog", "Activation\n"
"Calculation\n"
"(ReLU)"))
        self.customBiasEqualization_GroupBox.setTitle(_translate("Dialog", "Bias Equalization"))
        self.customBiasEqualization_Button.setText(_translate("Dialog", "Bias Equalization"))
        self.customBiasEqualizationDelete_Button.setText(_translate("Dialog", "Delete"))
        self.customBiasEqualizationAdd_Button.setText(_translate("Dialog", "Add"))
        self.customErrorSend_Button.setText(_translate("Dialog", "Error Send"))
        self.customActivationExtract_Button.setText(_translate("Dialog", "Activation\n"
"Extract"))
        self.customCycleMarker_Button.setText(_translate("Dialog", "Cycle Marker"))
        self.randomizeActivationInsert_GroupBox.setTitle(_translate("Dialog", "Randomize Activation Input"))
        self.customUniformRandomActivationInsert_Button.setText(_translate("Dialog", "Uniform Rand.\n"
"Act. Insert"))
        self.customNormalRandomActivationInsert_Button.setText(_translate("Dialog", "Normal Rand.\n"
"Act. Insert"))
        self.customRandomActivationCriteria_Label.setText(_translate("Dialog", "Maximum or SD"))
        self.customOutputLayerErrorCalculationLinear_Button.setText(_translate("Dialog", "Output Layer\n"
"Error Calc.\n"
"(Linear)"))
        self.customLayerActivationCalculationLinear_Button.setText(_translate("Dialog", "Activation\n"
"Calculation\n"
"(Linear)"))
        self.customHiddenLayerErrorCalculationLinear_Button.setText(_translate("Dialog", "Hidden Layer\n"
"Error Calc.\n"
"(Linear)"))
        self.customHiddenLayerErrorCalculationTanh_Button.setText(_translate("Dialog", "Hidden Layer\n"
"Error Calc.\n"
"(Tanh)"))
        self.customLayerActivationCalculationTanh_Button.setText(_translate("Dialog", "Activation\n"
"Calculation\n"
"(Tanh)"))
        self.customOutputLayerErrorCalculationTanh_Button.setText(_translate("Dialog", "Output Layer\n"
"Error Calc.\n"
"(Tanh)"))
        self.order_TapWidget.setTabText(self.order_TapWidget.indexOf(self.custom_Tap), _translate("Dialog", "Custom Order"))
        self.processSave_Button.setText(_translate("Dialog", "Process Save"))
        self.processLoad_Button.setText(_translate("Dialog", "Process Load"))
        self.exit_Button.setText(_translate("Dialog", "Exit"))

from . import Image_Resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

